# Generated by Django 2.0 on 2018-07-30 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('host_name', models.CharField(max_length=30, unique=True)),
                ('redirect_url', models.CharField(max_length=400, unique=True)),
                ('client_id', models.CharField(max_length=200, unique=True)),
                ('app_secret', models.CharField(max_length=400, unique=True)),
                ('login_redirect', models.CharField(max_length=50)),
                ('scope', models.CharField(default='vote,comment_options,comment,offline', max_length=200)),
                ('icon_address', models.CharField(max_length=400)),
                ('ms', models.CharField(max_length=500)),
                ('management', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_steemconnect.Community')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SteemConnectUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refresh_token', models.CharField(help_text='steemconnect user code / to get get_refresh_token', max_length=500)),
                ('code', models.CharField(help_text='steemconnect user code / to get get_refresh_token', max_length=500)),
                ('access_token', models.CharField(help_text='steemconnect user access_token to any operations', max_length=500)),
                ('community', models.ForeignKey(default=1, help_text='community', on_delete=django.db.models.deletion.CASCADE, to='django_steemconnect.Community')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
