# Generated by Django 2.0 on 2018-07-03 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Steemconnect_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refresh_token', models.CharField(help_text='steemconnect user code / to get get_refresh_token', max_length=500)),
                ('code', models.CharField(help_text='steemconnect user code / to get get_refresh_token', max_length=500)),
                ('access_token', models.CharField(help_text='steemconnect user access_token to any operations', max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
