# Generated by Django 2.0 on 2018-07-04 18:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_steemconnect', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Steemconnect_model',
            new_name='SteemConnectUser',
        ),
    ]
