# Generated by Django 2.0 on 2018-07-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_steemconnect', '0002_auto_20180704_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='steemconnectuser',
            name='community_name',
            field=models.CharField(default=1, help_text='community name', max_length=100),
            preserve_default=False,
        ),
    ]
