# Generated by Django 2.0.1 on 2018-01-29 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cooggerapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contentviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooggerapp.Content')),
            ],
        ),
    ]
