# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-14 20:25
from __future__ import unicode_literals

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('url', models.SlugField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=50)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('url', models.SlugField(max_length=100, unique=True)),
                ('comment', models.CharField(max_length=210)),
                ('hmcomment', models.IntegerField()),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Contents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.CharField(choices=[('SW', 'software'), ('EAE', 'electriciy and electronics')], default='SW', max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('url', models.SlugField(max_length=100, unique=True)),
                ('tag', models.CharField(max_length=100)),
                ('content', ckeditor.fields.RichTextField()),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('url', models.SlugField(max_length=100, unique=True)),
                ('hmlike', models.IntegerField()),
                ('hmdislike', models.IntegerField()),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
