# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-16 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_auto_20170916_0227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='username',
        ),
        migrations.AlterField(
            model_name='content',
            name='branch',
            field=models.CharField(choices=[('MAC', 'Makine'), ('EAE', 'Elektrik ve elektronik'), ('FOOD', 'Gıda'), ('PHY', 'Fizik'), ('CIV', 'İnşaat'), ('TEX', 'Tekstil'), ('IND', 'Endüstri'), ('COM', 'Bigisayar'), ('SOF', 'Yazılım'), ('MAM', 'Metalurji ve malzeme'), ('ENS', 'Enerji sistemleri'), ('BAC', 'Biyoproses ve kimya'), ('OAA', 'Optik ve akustik'), ('IMU', 'Dahili tıp birimleri'), ('SMU', 'Cerrahi tıp birimleri'), ('BMU', 'Temel tıp birimleri'), ('HIS', 'Tarih'), ('MAT', 'Matematik'), ('TLL', 'Türk dili ve edebiyat'), ('BİO', 'Biyoloji'), ('WLL', 'Batı dilleri ve edebiyat'), ('CHE', 'Kimya'), ('ARCH', 'Arkeoloji'), ('SOCİ', 'Sosyoloji'), ('PRCA', 'Kültür varlıklarını koruma ve onarım'), ('STA', 'İstatislik'), ('PSYCH', 'Psikoloji'), ('GEO', 'Çoğrafya'), ('PHİ', 'Felsefe'), ('ELL', 'Doğu dilleri ve edebiyatı'), ('', 'İktisat'), ('', 'İşletme'), ('', 'Uluslar arası ticaret ve lojistik'), ('', 'Kamu yönetim'), ('', 'Maliye'), ('', 'Küresel siyaset ve uluslararası ilişkiler'), ('', 'Matematik ve fen bilimleri'), ('', 'Güzel sanatlar'), ('', 'Türkçe ve sosyal bilimler'), ('', 'Yabancı diller'), ('', 'Eğitim yönetimi anabilim dalı'), ('', 'Eğitim programları ve öğretim adabilim dalı'), ('', 'Rehberlik ve psikojik danışma anabilim dalı'), ('', 'Eğitimin felsefesi,sosyal ve tarihi temelleri anabilim dalı'), ('', 'Hayar boyu öğrenme ve yetişkin eğitimi anabilim dalı'), ('', 'Öğretim teknolojileri anabilim dalı'), ('', 'Eğitimde ölçme ve değerlendirme anabilim dalı'), ('', 'Bilgisayar ve öğretim teknolojileri'), ('', 'Okul öncesi eğitimi anabilim dalı'), ('', 'Sınıf eğitimi anabilim dalı'), ('', 'Özel yetenekliler eğitimi anabilim dalı'), ('', 'Zihinsel engelliler eğitimi anabilim dalı'), ('', 'Görme engelliler eğitimi anabilim dalı'), ('', 'İşitme engelliler eğitimi anabilim dalı'), ('', 'eğitimi anabilim dalı'), ('', 'Ağız Diş ve Çene Cerrahisi AD.'), ('', 'Endodonti AD.'), ('', 'Oral Diagnoz ve Radyoloji AD.'), ('', 'Ortodonti AD.'), ('', 'Pedodonti AD.'), ('', 'Periodontoloji AD.'), ('', 'Protetik Diş Tedavisi AD.'), ('', 'Restoratif Diş Tedavisi AD.'), ('', 'ŞEHİR VE BÖLGE PLANLAMA BÖLÜMÜ'), ('', 'ENDÜSTRİ ÜRÜNLERİ TASARIMI BÖLÜMÜ'), ('', 'MİMARLIK BÖLÜMÜ'), ('', 'İÇ MİMARLIK BÖLÜMÜ'), ('', 'EKONOMETRİ'), ('', 'ULUSLARARASI İLİŞKİLER'), ('', 'MALİYE'), ('', 'KAMU YÖNETİMİ'), ('', 'İKTİSAT'), ('', 'İŞLETME'), ('', 'GASTRONOMİ VE MUTFAK SANATLARI BÖLÜMÜ'), ('', 'MODA VE TEKSTİL TASARIMI BÖLÜMÜ'), ('', 'SAHNE VE GÖSTERİ SANATLARI BÖLÜMÜ'), ('', 'GELENEKSEL TÜRK EL SANATLARI BÖLÜMÜ'), ('', 'SİNEMA VE TELEVİZYON BÖLÜMÜ'), ('', 'FOTOĞRAF BÖLÜMÜ'), ('', 'SERAMİK VE CAM BÖLÜMÜ'), ('', 'RESİM BÖLÜMÜ'), ('', 'HEYKEL BÖLÜMÜ'), ('', 'GRAFİK BÖLÜMÜ'), ('', 'FİZYOTERAPİ VE REHABİLİTASYON'), ('', 'DİL VE KONUŞMA TERAPİSİ'), ('', 'ODYOLOJİ'), ('', 'BESLENME VE DİYETETİK'), ('', 'SAĞLIK YÖNETİMİ'), ('', 'SOLUNUM TERAPİSTLİĞİ'), ('', 'EBELİK'), ('', 'HEMŞİRELİK'), ('', 'HUKUK FAKÜLTESİ'), ('', 'ANAYASA HUKUKU ANABİLİM DALI'), ('', 'CEZA VE CEZA MUHAKEMESİ HUKUKU ANABİLİM DALI'), ('', 'GENEL KAMU HUKUKU ANABİLİM DALI'), ('', 'HUKUK FELSEFESİ VE SOSYOLOJİSİ ANABİLİM DALI'), ('', 'HUKUK TARİHİ ANABİLİM DALI'), ('', 'MALİ HUKUK ANABİLİM DALI'), ('', 'MİLLETLERARASI HUKUK ANABİLİM DALI'), ('', 'İDARE HUKUKU ANABİLİM DALI'), ('', 'İNSAN HAKLARI ANABİLİM DALI'), ('', 'İSLAM HUKUKU ANABİLİM DALI'), ('', 'TİCARET HUKUKU ANABİLİM DALI'), ('', 'AVRUPA BİRLİĞİ HUKUKU ANABİLİM DALI'), ('', 'DENİZ HUKUKU ANABİLİM DALI'), ('', 'KARŞILAŞTIRMALI HUKUK ANABİLİM DALI'), ('', 'MEDENİ HUKUK ANABİLİM DALI'), ('', 'MEDENİ USUL VE İCRA İFLAS HUKUKU ANABİLİM DALI'), ('', 'MİLLETLERARASI ÖZEL HUKUK ANABİLİM DALI'), ('', 'ROMA HUKUKU ANABİLİM DALI'), ('', 'İŞ VE SOSYAL GÜVENLİK HUKUKU ANABİLİM DALI'), ('', 'Tefsir'), ('', 'Hadis'), ('', 'Kelam'), ('', 'İslam Hukuku'), ('', 'İslam Mezhepleri Tarihi'), ('', 'Tasavvuf'), ('', 'Arap Dili ve Belagatı'), ('', 'Kuranı Kerim Okuma ve Kıraat İlmi'), ('', 'Din Eğitimi'), ('', 'Dinler Tarihi'), ('', 'İslam Felsefesi'), ('', 'Din Sosyolojisi'), ('', 'Din Psikolojisi'), ('', 'Felsefe Tarihi'), ('', 'Mantık'), ('', 'İslam Tarihi'), ('', 'Türk İslam Edebiyatı'), ('', 'Türk İslam Sanatları Tarihi'), ('', 'Türk Din Musikisi'), ('', 'Gazetecilik'), ('', 'Halkla ilişkiler ve tanıtım'), ('', 'Radyo, tv ve sinema'), ('', 'İletişim enformatiği'), ('', 'Reklamcılık'), ('', 'HAVACILIK YÖNETİMİ BÖLÜMÜ'), ('', 'UÇAK VE UZAY MÜHENDİSLİĞİ BÖLÜMÜ'), ('', 'PİLOTAJ BÖLÜMÜ')], max_length=5),
        ),
        migrations.AlterField(
            model_name='content',
            name='fields',
            field=models.CharField(choices=[('EN', 'Mühendislik'), ('ME', 'Tıp'), ('SL', 'Fen-edebiyat'), ('EAAS', 'İktisadi ve idari bilimleri'), ('ED', 'Eğitim'), ('DE', 'Diş hekimliği'), ('ARC', 'Mimarlık'), ('IEAAS', 'İslahiye iktisadi ve idari bilimleri'), ('FI', 'Güzel sanatlar'), ('HE', 'Sağlık bilimleri'), ('LA', 'Hukuk'), ('TH', 'İlahiyat'), ('CO', 'İletişim'), ('AE', 'Havacılık ve uzay mühendisliği'), ('TO', 'Turizm'), ('TMC', 'Türk musıkisi devlet konservatuarı'), ('PES', 'Beden eğitimi ve spor'), ('FL', 'Yabancı diller'), ('CA', 'Sivil havacılık'), ('TS', 'Teknik bilimler'), ('LA', 'Sosyal bilimler'), ('HC', 'Sağlık hizmetleri'), ('THM', 'Turizm ve Otelcilik'), ('IS', 'Islahiye')], max_length=5),
        ),
    ]
