class Category: 
    "kategoriler eylence/ders/"
    def __init__(self):
        self.category = [
            "ders",
            "oyun",
            "seyahat",
            "giyim",
            "makyaj ve cilt bakım",
            "sağlık",
            "yiyecek ve içecek",
            "medya",
            "ürün eşya",
            "taşıtlar",
            "tanınmış kişi",
            "hayvanlar",
            "inanç",
            "dil",
            "metafizik",
            "aşk arkadaşlık"
            ]

class Subcategory:
    "alt kategori"
    def ders():
        faculties = [
            # fakülteler
            'Mühendislik',
            "Tıp",
            "Fen edebiyat",
            "İktisadi ve idari bilimleri",
            "Eğitim",
            "Diş hekimliği",
            "Mimarlık",
            "İslahiye iktisadi ve idari bilimleri",
            "Güzel sanatlar",
            "Sağlık bilimleri",
            "Hukuk",
            "İlahiyat",
            "İletişim",
            "Havacılık ve uzay mühendisliği",
            "Turizm"
        ]
        yüksekokul = [
            # yüksekokular
            "Türk musıkisi devlet konservatuarı",
            "Beden eğitimi ve spor",
            "Yabancı diller",
            "Sivil havacılık",
        ]
        meslek_yüksekokul = [
            # meslek yüksek okullar
            "Teknik bilimler",
            "Sosyal bilimler",
            "Sağlık hizmetleri",
            "Turizm ve Otelcilik",
            "Islahiye",
            "BÜRO HİZMETLERİ VE SEKRETERLİK BÖLÜMÜ",
            "BİLGİSAYAR TEKNOLOJİLERİ BÖLÜMÜ",
            "BİTKİSEL VE HAYVANSAL ÜRETİMİ BÖLÜMÜ",
            "FİNANS VE BANKACILIK BÖLÜMÜ",
            "GIDA İŞLEMLERİ BÖLÜMÜ",
            "DIŞ TİCARET BÖLÜMÜ",
            "YÖNETİM VE ORGANİZASYON BÖLÜMÜ",
            "PAZARLAMA VE REKLAMCILIK BÖLÜMÜ",
            "TERAPİ VE REHABİLİTASYON BÖLÜMÜ",
            "SAĞLIK BAKIM HİZMETLERİ BÖLÜMÜ",
            "DİŞÇİLİK HİZMETLERİ BÖLÜMÜ",
            "OTEL, LOKANTA VE İKRAM HİZMETLERİ BÖLÜMÜ",
            "SEYAHAT-TURİZM VE EĞLENCE HİZMETLERİ BÖLÜMÜ",
            "Adalet",
            "Lojistik",
            "İşletme Yönetimi",
            "İş Sağlığı ve Güvenliği",
            "Bilgisayar Programcılığı",
            "Özel Güvenlik ve Koruma",
            "Sivil Savunma ve İtfaiyecilik",
            "Sosyal Güvenlik",
            "MÜLKİYETİ KORUMA VE GÜVENLİK BÖLÜMÜ",
            "VETERİNERLİK BÖLÜMÜ",
            "MUHASEBE VE VERGİ BÖLÜMÜ",
            "Dış ticaret",
            "Yönetim ve organizasyon",
            "Bitkisel ve hayvansal üretim",
            "el sanatları",
            "gıda işleme",
            "malzeme ve malzeme işleme",
            "tekstil,giyim,ayakkabı,deri",
            "mülkiyet koruma ve güvenlik",
            "makine ve metal teknolojileri",
            "kimya ve kimyasal işleme teknolojileri",
            "TIBBİ HİZMETLER VE TEKNİKLER BÖLÜMÜ",
            "BİTKİSEL VE HAYVANSAL ÜRETİM BÖLÜMÜ",
            ]
        return faculties
    def oyun():
        pc_games = [
            "grand theft auto",
            "counter strike global offensive",
            "euro truck simulator",
            "minecraft",
            "fifa",
            "battlefield",
            "call of duty",
            "prey",
            "watch dogs",
            "fallout",
            "far cry",
            "half-life",
            "assassin's creed",
            "league of legends",
            "destiny",
            "rise of the tomb raider",
        ]
        mobile_games = [
            "clash of clans",
        ]
        return pc_games + mobile_games

    def seyahat():
        name_of_cities = [
            "adana",
            "adıyaman",
            "afyon",
            "ağrı",
            "amasya",
            "ankara",
            "antalya",
            "artvin",
            "aydın",
            "balıkesir",
            "bilecik",
            "bingöl",
            "bitlis",
            "bolu",
            "burdur",
            "bursa",
            "çanakkale",
            "çankırı",
            "çorum",
            "denizli",
            "diyarbakır",
            "edirne",
            "elazığ",
            "erzincan",
            "erzurum",
            "eskişehir",
            "gaziantep",
            "giresun",
            "gümüşhane",
            "hakkari",
            "hatay",
            "ısparta",
            "mersin",
            "istanbul",
            "izmir",
            "kars",
            "kastamonu",
            "kayseri",
            "Kırklareli",
            "kırşehir",
            "kocaeli",
            "konya",
            "kütahya",
            "malatya",
            "manisa",
            "kahramanmaraş",
            "mardin",
            "muğla",
            "muş",
            "nevşehir",
            "niğde",
            "ordu",
            "rize",
            "sakarya",
            "samsun",
            "siirt",
            "sinop",
            "sivas",
            "tekirdağ",
            "tokat",
            "trabzon",
            "tunceli",
            "şanlıurfa",
            "uşak",
            "van",
            "yozgat",
            "zonguldak",
            "aksaray",
            "bayburt",
            "karaman",
            "kırıkkale",
            "batman",
            "şırnak",
            "bartın",
            "ardahan",
            "ığdır",
            "yalova",
            "karabuk",
            "kilis",
            "osmaniye",
            "düzce",
        ]
        return name_of_cities

    def giyim():
        clot = [
            "yazlık",
            "kışlık",
            "mevsimlik",
            "aksesuar",
        ]
        return clot
    def makyaj_ve_cilt_bakm():
        make = [
            "Günlük Makyaj",
            "Porselen Makyaj",
            "Show Makyajı",
            "Kalıcı Makyaj",
            "Gece Makyajı",
            "cilt bakımı",
        ]
        return make

    def yiyecek_ve_icecek():
        food = [
            "sulu",
            "çorbalar",
            "etli",
            "fastfood",
            "soğuk",
            "sıcak",
            "alkollu",
            "tatlılar",
            "tuzlu",
            "restorant",
            "pasta",
            "ev yemekleri",
        ]
        return food

    def medya():
        med = [
            "televiyon - program",
            "radyo",
            "sinema",
            "müzik",
            "kitap",
            "video",
            "ses",
        ]
        return med

    def urun_esya():
        pro = [
            "ev eşyaları",
            "teknolojik eşyalar",
        ]
        return pro

    def tastlar():
        ve = [
            "kara",
            "hava",
            "deniz",
        ]
        return ve

    def tannms_kisi():
        person = [
            "Bilim insanı",
            "siyaset insanı",
            "din insanı",
            "felsefe insanı",
            "sinema-oyuncusu",
            "müzisyen",
            "oyuncu - gamer",
            "yazar",
            "şarkıcı",
            "sporcu",
            "girişimci",
            "diğer",
        ]
        return person

    def hayvanlar():
        anim = [
            "sokak",
            "evcil",
            "vahşi",
        ]
        return anim

    def inanc():
        fa = [
            "dini",
            "kişisel",
        ]
        return fa

    def all(): # bütün alt kategorileri almak için
        all_ = [
            "Günlük Makyaj",
            "Porselen Makyaj",
            "Show Makyajı",
            "Kalıcı Makyaj",
            "Gece Makyajı",
            "cilt bakımı",
            "sulu",
            "çorbalar",
            "etli",
            "fastfood",
            "soğuk",
            "sıcak",
            "alkollu",
            "tatlılar",
            "tuzlu",
            "restorant",
            "pasta",
            "ev yemekleri",
            "televiyon - program",
            "radyo",
            "sinema",
            "müzik",
            "kitap",
            "video",
            "ses",
            "ev eşyaları",
            "teknolojik eşyalar",
            "kara",
            "hava",
            "deniz",
            "Bilim insanı",
            "siyaset insanı",
            "din insanı",
            "felsefe insanı",
            "sinema-oyuncusu",
            "müzisyen",
            "oyuncu - gamer",
            "yazar",
            "şarkıcı",
            "sporcu",
            "girişimci",
            "diğer",
            "sokak",
            "evcil",
            "vahşi",
            "dini",
            "kişisel",
            "Günlük Makyaj",
            "Porselen Makyaj",
            "Show Makyajı",
            "Kalıcı Makyaj",
            "Gece Makyajı",
            "cilt bakımı",
            'Mühendislik',
            "Tıp",
            "Fen edebiyat",
            "İktisadi ve idari bilimleri",
            "Eğitim",
            "Diş hekimliği",
            "Mimarlık",
            "İslahiye iktisadi ve idari bilimleri",
            "Güzel sanatlar",
            "Sağlık bilimleri",
            "Hukuk",
            "İlahiyat",
            "İletişim",
            "Havacılık ve uzay mühendisliği",
            "Turizm",
            "grand theft auto",
            "counter strike global offensive",
            "euro truck simulator",
            "minecraft",
            "fifa",
            "battlefield",
            "call of duty",
            "prey",
            "watch dogs",
            "fallout",
            "far cry",
            "half-life",
            "assassin's creed",
            "league of legends",
            "destiny",
            "rise of the tomb raider",
            "clash of clans",
            "adana",
            "adıyaman",
            "afyon",
            "ağrı",
            "amasya",
            "ankara",
            "antalya",
            "artvin",
            "aydın",
            "balıkesir",
            "bilecik",
            "bingöl",
            "bitlis",
            "bolu",
            "burdur",
            "bursa",
            "çanakkale",
            "çankırı",
            "çorum",
            "denizli",
            "diyarbakır",
            "edirne",
            "elazığ",
            "erzincan",
            "erzurum",
            "eskişehir",
            "gaziantep",
            "giresun",
            "gümüşhane",
            "hakkari",
            "hatay",
            "ısparta",
            "mersin",
            "istanbul",
            "izmir",
            "kars",
            "kastamonu",
            "kayseri",
            "Kırklareli",
            "kırşehir",
            "kocaeli",
            "konya",
            "kütahya",
            "malatya",
            "manisa",
            "kahramanmaraş",
            "mardin",
            "muğla",
            "muş",
            "nevşehir",
            "niğde",
            "ordu",
            "rize",
            "sakarya",
            "samsun",
            "siirt",
            "sinop",
            "sivas",
            "tekirdağ",
            "tokat",
            "trabzon",
            "tunceli",
            "şanlıurfa",
            "uşak",
            "van",
            "yozgat",
            "zonguldak",
            "aksaray",
            "bayburt",
            "karaman",
            "kırıkkale",
            "batman",
            "şırnak",
            "bartın",
            "ardahan",
            "ığdır",
            "yalova",
            "karabuk",
            "kilis",
            "osmaniye",
            "düzce",
            "yazlık",
            "kışlık",
            "mevsimlik",
            "aksesuar"
        ]
        return all_

class Category2:
    def muhendislik():
        en = [ # mühendislik dalları
            "Makine",
            "Elektrik ve elektronik",
            "Gıda",
            "Fizik",
            "İnşaat",
            "Tekstil",
            "Endüstri",
            "Bigisayar",
            "Yazılım",
            "Metalurji ve malzeme",
            "Enerji sistemleri",
            "Biyoproses ve kimya",
            "Optik ve akustik",
        ]
        return en

    def tp():
        me = [ # tıpın dalları
            "Dahili tıp birimleri",
            "Cerrahi tıp birimleri",
            "Temel tıp birimleri",
        ]
        return me

    def fen_edebiyat():
        sl = [ # fen edebiyat
            "Tarih",
            "Matematik",
            "Türk dili ve edebiyat",
            "Biyoloji",
            "Batı dilleri ve edebiyat",
            "Kimya",
            "Arkeoloji",
            "Sosyoloji",
            "Kültür varlıklarını koruma ve onarım",
            "İstatislik",
            "Psikoloji",
            "Çoğrafya",
            "Felsefe",
            "Doğu dilleri ve edebiyatı",
        ]
        return sl
    
    def iktisadi_ve_idari_bilimleri():
        eaas = [ # iktisadi ve  idari
            "İktisat",
            "İşletme",
            "Uluslar arası ticaret ve lojistik",
            "Kamu yönetim",
            "Maliye",
            "Küresel siyaset ve uluslararası ilişkiler",
        ]
        return eaas

    def egitim():
        ed = [ # eğitim
            "Matematik ve fen bilimleri",
            "Güzel sanatlar",
            "Türkçe ve sosyal bilimler",
            "Yabancı diller",
            "Eğitim yönetimi anabilim dalı",
            "Eğitim programları ve öğretim adabilim dalı",
            "Rehberlik ve psikojik danışma anabilim dalı",
            "Eğitimin felsefesi,sosyal ve tarihi temelleri anabilim dalı",
            "Hayat boyu öğrenme ve yetişkin eğitimi anabilim dalı",
            "Öğretim teknolojileri anabilim dalı",
            "Eğitimde ölçme ve değerlendirme anabilim dalı",
            "Bilgisayar ve öğretim teknolojileri",
            "Okul öncesi eğitimi anabilim dalı",
            "Sınıf eğitimi anabilim dalı",
            "Özel yetenekliler eğitimi anabilim dalı",
            "Zihinsel engelliler eğitimi anabilim dalı",
            "Görme engelliler eğitimi anabilim dalı",
            "İşitme engelliler eğitimi anabilim dalı",
            "eğitimi anabilim dalı",
        ]
        return ed

    def dis_hekimligi():
        de = [ # diş 
            "Ağız Diş ve Çene Cerrahisi AD.",
            "Endodonti AD.",
            "Oral Diagnoz ve Radyoloji AD.",
            "Ortodonti AD.",
            "Pedodonti AD.",
            "Periodontoloji AD.",
            "Protetik Diş Tedavisi AD.",
            "Restoratif Diş Tedavisi AD.",
        ]
        return de

    def mimarlk():
        arc = [ # mimar
            "ŞEHİR VE BÖLGE PLANLAMA BÖLÜMÜ",
            "ENDÜSTRİ ÜRÜNLERİ TASARIMI BÖLÜMÜ",
            "MİMARLIK BÖLÜMÜ",
            "İÇ MİMARLIK BÖLÜMÜ",
        ]
        return arc

    def islahiye_iktisadi_ve_idari_bilimleri():
        ieaas = [ # İslahiye İktisadi ve İdari Bilimler Fakültesi
            "EKONOMETRİ",
            "ULUSLARARASI İLİŞKİLER",
            "MALİYE",
            "KAMU YÖNETİMİ",
            "İKTİSAT",
            "İŞLETME",
        ]
        return ieaas

    def guzel_sanatlar():
        fi = [ # güzel sanatlar
            "GASTRONOMİ VE MUTFAK SANATLARI BÖLÜMÜ",
            "MODA VE TEKSTİL TASARIMI BÖLÜMÜ",
            "SAHNE VE GÖSTERİ SANATLARI BÖLÜMÜ",
            "GELENEKSEL TÜRK EL SANATLARI BÖLÜMÜ",
            "SİNEMA VE TELEVİZYON BÖLÜMÜ",
            "FOTOĞRAF BÖLÜMÜ",
            "SERAMİK VE CAM BÖLÜMÜ",
            "RESİM BÖLÜMÜ",
            "HEYKEL BÖLÜMÜ",
            "GRAFİK BÖLÜMÜ",
        ]
        return fi

    def saglk_bilimleri():
        he = [ #sağlık
            "FİZYOTERAPİ VE REHABİLİTASYON",
            "DİL VE KONUŞMA TERAPİSİ",
            "ODYOLOJİ",
            "BESLENME VE DİYETETİK",
            "SAĞLIK YÖNETİMİ",
            "SOLUNUM TERAPİSTLİĞİ",
            "EBELİK",
            "HEMŞİRELİK",
        ]
        return he

    def hukuk():
        la = [ # hukuk 
            "HUKUK FAKÜLTESİ", 
            "ANAYASA HUKUKU ANABİLİM DALI", 
            "CEZA VE CEZA MUHAKEMESİ HUKUKU ANABİLİM DALI", 
            "GENEL KAMU HUKUKU ANABİLİM DALI", 
            "HUKUK FELSEFESİ VE SOSYOLOJİSİ ANABİLİM DALI", 
            "HUKUK TARİHİ ANABİLİM DALI", 
            "MALİ HUKUK ANABİLİM DALI", 
            "MİLLETLERARASI HUKUK ANABİLİM DALI", 
            "İDARE HUKUKU ANABİLİM DALI", 
            "İNSAN HAKLARI ANABİLİM DALI", 
            "İSLAM HUKUKU ANABİLİM DALI", 
            "TİCARET HUKUKU ANABİLİM DALI", 
            "AVRUPA BİRLİĞİ HUKUKU ANABİLİM DALI", 
            "DENİZ HUKUKU ANABİLİM DALI", 
            "KARŞILAŞTIRMALI HUKUK ANABİLİM DALI", 
            "MEDENİ HUKUK ANABİLİM DALI", 
            "MEDENİ USUL VE İCRA İFLAS HUKUKU ANABİLİM DALI",
            "MİLLETLERARASI ÖZEL HUKUK ANABİLİM DALI", 
            "ROMA HUKUKU ANABİLİM DALI", 
            "İŞ VE SOSYAL GÜVENLİK HUKUKU ANABİLİM DALI",
        ]
        return la

    def ilahiyat():
        th = [ # ilahiyat
            "Tefsir",
            "Hadis",
            "Kelam",
            "İslam Hukuku",
            "İslam Mezhepleri Tarihi",
            "Tasavvuf",
            "Arap Dili ve Belagatı",
            "Kuranı Kerim Okuma ve Kıraat İlmi",
            "Din Eğitimi",
            "Dinler Tarihi",
            "İslam Felsefesi",
            "Din Sosyolojisi",
            "Din Psikolojisi",
            "Felsefe Tarihi",
            "Mantık",
            "İslam Tarihi",
            "Türk İslam Edebiyatı",
            "Türk İslam Sanatları Tarihi",
            "Türk Din Musikisi",
        ]
        return th

    def iletisim():
        co = [ # iletişim
            "Gazetecilik",
            "Halkla ilişkiler ve tanıtım",
            "Radyo, tv ve sinema",
            "İletişim enformatiği",
            "Reklamcılık",
        ]
        return co

    def havaclk_ve_uzay_mühendisligi():
        ae = [ # HAVACILIK VE UZAY BİLİMLERİ FAKÜLTESİ
            "HAVACILIK YÖNETİMİ BÖLÜMÜ",
            "UÇAK VE UZAY MÜHENDİSLİĞİ BÖLÜMÜ",
            "PİLOTAJ BÖLÜMÜ",
        ]
        return ae
    def all():
        all_ = [
            "Makine",
            "Elektrik ve elektronik",
            "Gıda",
            "Fizik",
            "İnşaat",
            "Tekstil",
            "Endüstri",
            "Bigisayar",
            "Yazılım",
            "Metalurji ve malzeme",
            "Enerji sistemleri",
            "Biyoproses ve kimya",
            "Optik ve akustik",
            "Dahili tıp birimleri",
            "Cerrahi tıp birimleri",
            "Temel tıp birimleri",
            "Tarih",
            "Matematik",
            "Türk dili ve edebiyat",
            "Biyoloji",
            "Batı dilleri ve edebiyat",
            "Kimya",
            "Arkeoloji",
            "Sosyoloji",
            "Kültür varlıklarını koruma ve onarım",
            "İstatislik",
            "Psikoloji",
            "Çoğrafya",
            "Felsefe",
            "Doğu dilleri ve edebiyatı",
            "İktisat",
            "İşletme",
            "Uluslar arası ticaret ve lojistik",
            "Kamu yönetim",
            "Maliye",
            "Küresel siyaset ve uluslararası ilişkiler",
            "Matematik ve fen bilimleri",
            "Güzel sanatlar",
            "Türkçe ve sosyal bilimler",
            "Yabancı diller",
            "Eğitim yönetimi anabilim dalı",
            "Eğitim programları ve öğretim adabilim dalı",
            "Rehberlik ve psikojik danışma anabilim dalı",
            "Eğitimin felsefesi,sosyal ve tarihi temelleri anabilim dalı",
            "Hayat boyu öğrenme ve yetişkin eğitimi anabilim dalı",
            "Öğretim teknolojileri anabilim dalı",
            "Eğitimde ölçme ve değerlendirme anabilim dalı",
            "Bilgisayar ve öğretim teknolojileri",
            "Okul öncesi eğitimi anabilim dalı",
            "Sınıf eğitimi anabilim dalı",
            "Özel yetenekliler eğitimi anabilim dalı",
            "Zihinsel engelliler eğitimi anabilim dalı",
            "Görme engelliler eğitimi anabilim dalı",
            "İşitme engelliler eğitimi anabilim dalı",
            "eğitimi anabilim dalı",
            "Ağız Diş ve Çene Cerrahisi AD.",
            "Endodonti AD.",
            "Oral Diagnoz ve Radyoloji AD.",
            "Ortodonti AD.",
            "Pedodonti AD.",
            "Periodontoloji AD.",
            "Protetik Diş Tedavisi AD.",
            "Restoratif Diş Tedavisi AD.",
            "ŞEHİR VE BÖLGE PLANLAMA BÖLÜMÜ",
            "ENDÜSTRİ ÜRÜNLERİ TASARIMI BÖLÜMÜ",
            "MİMARLIK BÖLÜMÜ",
            "İÇ MİMARLIK BÖLÜMÜ",
            "EKONOMETRİ",
            "ULUSLARARASI İLİŞKİLER",
            "MALİYE",
            "KAMU YÖNETİMİ",
            "İKTİSAT",
            "İŞLETME",
            "GASTRONOMİ VE MUTFAK SANATLARI BÖLÜMÜ",
            "MODA VE TEKSTİL TASARIMI BÖLÜMÜ",
            "SAHNE VE GÖSTERİ SANATLARI BÖLÜMÜ",
            "GELENEKSEL TÜRK EL SANATLARI BÖLÜMÜ",
            "SİNEMA VE TELEVİZYON BÖLÜMÜ",
            "FOTOĞRAF BÖLÜMÜ",
            "SERAMİK VE CAM BÖLÜMÜ",
            "RESİM BÖLÜMÜ",
            "HEYKEL BÖLÜMÜ",
            "GRAFİK BÖLÜMÜ",
            "FİZYOTERAPİ VE REHABİLİTASYON",
            "DİL VE KONUŞMA TERAPİSİ",
            "ODYOLOJİ",
            "BESLENME VE DİYETETİK",
            "SAĞLIK YÖNETİMİ",
            "SOLUNUM TERAPİSTLİĞİ",
            "EBELİK",
            "HEMŞİRELİK",
            "HUKUK FAKÜLTESİ", 
            "ANAYASA HUKUKU ANABİLİM DALI", 
            "CEZA VE CEZA MUHAKEMESİ HUKUKU ANABİLİM DALI", 
            "GENEL KAMU HUKUKU ANABİLİM DALI", 
            "HUKUK FELSEFESİ VE SOSYOLOJİSİ ANABİLİM DALI", 
            "HUKUK TARİHİ ANABİLİM DALI", 
            "MALİ HUKUK ANABİLİM DALI", 
            "MİLLETLERARASI HUKUK ANABİLİM DALI", 
            "İDARE HUKUKU ANABİLİM DALI", 
            "İNSAN HAKLARI ANABİLİM DALI", 
            "İSLAM HUKUKU ANABİLİM DALI", 
            "TİCARET HUKUKU ANABİLİM DALI", 
            "AVRUPA BİRLİĞİ HUKUKU ANABİLİM DALI", 
            "DENİZ HUKUKU ANABİLİM DALI", 
            "KARŞILAŞTIRMALI HUKUK ANABİLİM DALI", 
            "MEDENİ HUKUK ANABİLİM DALI", 
            "MEDENİ USUL VE İCRA İFLAS HUKUKU ANABİLİM DALI",
            "MİLLETLERARASI ÖZEL HUKUK ANABİLİM DALI", 
            "ROMA HUKUKU ANABİLİM DALI", 
            "İŞ VE SOSYAL GÜVENLİK HUKUKU ANABİLİM DALI",
            "Tefsir",
            "Hadis",
            "Kelam",
            "İslam Hukuku",
            "İslam Mezhepleri Tarihi",
            "Tasavvuf",
            "Arap Dili ve Belagatı",
            "Kuranı Kerim Okuma ve Kıraat İlmi",
            "Din Eğitimi",
            "Dinler Tarihi",
            "İslam Felsefesi",
            "Din Sosyolojisi",
            "Din Psikolojisi",
            "Felsefe Tarihi",
            "Mantık",
            "İslam Tarihi",
            "Türk İslam Edebiyatı",
            "Türk İslam Sanatları Tarihi",
            "Türk Din Musikisi",
            "Gazetecilik",
            "Halkla ilişkiler ve tanıtım",
            "Radyo, tv ve sinema",
            "İletişim enformatiği",
            "Reklamcılık",
            "HAVACILIK YÖNETİMİ BÖLÜMÜ",
            "UÇAK VE UZAY MÜHENDİSLİĞİ BÖLÜMÜ",
            "PİLOTAJ BÖLÜMÜ",
        ]
        return all_

        
