class Category: 
    "kategoriler eylence/ders/"
    def __init__(self):
        self.category = [
            "ders",
            "oyun",
            "seyahat",
            "giyim",
            "makyaj ve cilt bakım",
            "sağlık",
            "yiyecek ve içecek",
            "medya",
            "ürün eşya",
            "taşıtlar",
            "tanınmış kişi",
            "hayvanlar",
            "inanç",
            "dil",
            "metafizik",
            "aşk arkadaşlık"
            ]

class Subcategory:
    "alt kategori"
    def ders():
        faculties = [
            # fakülteler
            'Mühendislik',
            "Tıp",
            "Fen edebiyat",
            "İktisadi ve idari bilimleri",
            "Eğitim",
            "Diş hekimliği",
            "Mimarlık",
            "İslahiye iktisadi ve idari bilimleri",
            "Güzel sanatlar",
            "Sağlık bilimleri",
            "Hukuk",
            "İlahiyat",
            "İletişim",
            "Havacılık ve uzay mühendisliği",
            "Turizm"
        ]
        yüksekokul = [
            # yüksekokular
            "Türk musıkisi devlet konservatuarı",
            "Beden eğitimi ve spor",
            "Yabancı diller",
            "Sivil havacılık",
        ]
        meslek_yüksekokul = [
            # meslek yüksek okullar
            "Teknik bilimler",
            "Sosyal bilimler",
            "Sağlık hizmetleri",
            "Turizm ve Otelcilik",
            "Islahiye",
            "BÜRO HİZMETLERİ VE SEKRETERLİK BÖLÜMÜ",
            "BİLGİSAYAR TEKNOLOJİLERİ BÖLÜMÜ",
            "BİTKİSEL VE HAYVANSAL ÜRETİMİ BÖLÜMÜ",
            "FİNANS VE BANKACILIK BÖLÜMÜ",
            "GIDA İŞLEMLERİ BÖLÜMÜ",
            "DIŞ TİCARET BÖLÜMÜ",
            "YÖNETİM VE ORGANİZASYON BÖLÜMÜ",
            "PAZARLAMA VE REKLAMCILIK BÖLÜMÜ",
            "TERAPİ VE REHABİLİTASYON BÖLÜMÜ",
            "SAĞLIK BAKIM HİZMETLERİ BÖLÜMÜ",
            "DİŞÇİLİK HİZMETLERİ BÖLÜMÜ",
            "OTEL, LOKANTA VE İKRAM HİZMETLERİ BÖLÜMÜ",
            "SEYAHAT-TURİZM VE EĞLENCE HİZMETLERİ BÖLÜMÜ",
            "Adalet",
            "Lojistik",
            "İşletme Yönetimi",
            "İş Sağlığı ve Güvenliği",
            "Bilgisayar Programcılığı",
            "Özel Güvenlik ve Koruma",
            "Sivil Savunma ve İtfaiyecilik",
            "Sosyal Güvenlik",
            "MÜLKİYETİ KORUMA VE GÜVENLİK BÖLÜMÜ",
            "VETERİNERLİK BÖLÜMÜ",
            "MUHASEBE VE VERGİ BÖLÜMÜ",
            "Dış ticaret",
            "Yönetim ve organizasyon",
            "Bitkisel ve hayvansal üretim",
            "el sanatları",
            "gıda işleme",
            "malzeme ve malzeme işleme",
            "tekstil,giyim,ayakkabı,deri",
            "mülkiyet koruma ve güvenlik",
            "makine ve metal teknolojileri",
            "kimya ve kimyasal işleme teknolojileri",
            "TIBBİ HİZMETLER VE TEKNİKLER BÖLÜMÜ",
            "BİTKİSEL VE HAYVANSAL ÜRETİM BÖLÜMÜ",
            ]
        return faculties
    def oyun():
        pc_games = [
            "grand theft auto",
            "counter strike global offensive",
            "euro truck simulator",
            "minecraft",
            "fifa",
            "battlefield",
            "call of duty",
            "prey",
            "watch dogs",
            "fallout",
            "far cry",
            "half-life",
            "assassin's creed",
            "league of legends",
            "destiny",
            "rise of the tomb raider",
        ]
        mobile_games = [
            "clash of clans",
        ]
        return pc_games + mobile_games

    def seyahat():
        name_of_cities = [
            "adana",
            "adıyaman",
            "afyon",
            "ağrı",
            "amasya",
            "ankara",
            "antalya",
            "artvin",
            "aydın",
            "balıkesir",
            "bilecik",
            "bingöl",
            "bitlis",
            "bolu",
            "burdur",
            "bursa",
            "çanakkale",
            "çankırı",
            "çorum",
            "denizli",
            "diyarbakır",
            "edirne",
            "elazığ",
            "erzincan",
            "erzurum",
            "eskişehir",
            "gaziantep",
            "giresun",
            "gümüşhane",
            "hakkari",
            "hatay",
            "ısparta",
            "mersin",
            "istanbul",
            "izmir",
            "kars",
            "kastamonu",
            "kayseri",
            "Kırklareli",
            "kırşehir",
            "kocaeli",
            "konya",
            "kütahya",
            "malatya",
            "manisa",
            "kahramanmaraş",
            "mardin",
            "muğla",
            "muş",
            "nevşehir",
            "niğde",
            "ordu",
            "rize",
            "sakarya",
            "samsun",
            "siirt",
            "sinop",
            "sivas",
            "tekirdağ",
            "tokat",
            "trabzon",
            "tunceli",
            "şanlıurfa",
            "uşak",
            "van",
            "yozgat",
            "zonguldak",
            "aksaray",
            "bayburt",
            "karaman",
            "kırıkkale",
            "batman",
            "şırnak",
            "bartın",
            "ardahan",
            "ığdır",
            "yalova",
            "karabuk",
            "kilis",
            "osmaniye",
            "düzce",
        ]
        return name_of_cities

    def giyim():
        clot = [
            "yazlık",
            "kışlık",
            "mevsimlik",
            "aksesuar",
        ]
        return clot
    def makyaj_ve_cilt_bakm():
        make = [
            "Günlük Makyaj",
            "Porselen Makyaj",
            "Show Makyajı",
            "Kalıcı Makyaj",
            "Gece Makyajı",
            "cilt bakımı",
        ]
        return make

    def yiyecek_ve_icecek():
        food = [
            "sulu",
            "çorbalar",
            "etli",
            "fastfood",
            "soğuk",
            "sıcak",
            "alkollu",
            "tatlılar",
            "tuzlu",
            "restorant",
            "pasta",
            "ev yemekleri",
        ]
        return food

    def medya():
        med = [
            "televiyon - program",
            "radyo",
            "sinema",
            "müzik",
            "kitap",
            "video",
            "ses",
        ]
        return med

    def urun_esya():
        pro = [
            "ev eşyaları",
            "teknolojik eşyalar",
        ]
        return pro

    def tastlar():
        ve = [
            "kara",
            "hava",
            "deniz",
        ]
        return ve

    def tannms_kisi():
        person = [
            "Bilim insanı",
            "siyaset insanı",
            "din insanı",
            "felsefe insanı",
            "sinema-oyuncusu",
            "müzisyen",
            "oyuncu - gamer",
            "yazar",
            "şarkıcı",
            "sporcu",
            "girişimci",
            "diğer",
        ]
        return person

    def hayvanlar():
        anim = [
            "sokak",
            "evcil",
            "vahşi",
        ]
        return anim

    def inanc():
        fa = [
            "dini",
            "kişisel",
        ]
        return fa

    def all(): # bütün alt kategorileri almak için
        all_ = [
            "Günlük Makyaj",
            "Porselen Makyaj",
            "Show Makyajı",
            "Kalıcı Makyaj",
            "Gece Makyajı",
            "cilt bakımı",
            "sulu",
            "çorbalar",
            "etli",
            "fastfood",
            "soğuk",
            "sıcak",
            "alkollu",
            "tatlılar",
            "tuzlu",
            "restorant",
            "pasta",
            "ev yemekleri",
            "televiyon - program",
            "radyo",
            "sinema",
            "müzik",
            "kitap",
            "video",
            "ses",
            "ev eşyaları",
            "teknolojik eşyalar",
            "kara",
            "hava",
            "deniz",
            "Bilim insanı",
            "siyaset insanı",
            "din insanı",
            "felsefe insanı",
            "sinema-oyuncusu",
            "müzisyen",
            "oyuncu - gamer",
            "yazar",
            "şarkıcı",
            "sporcu",
            "girişimci",
            "diğer",
            "sokak",
            "evcil",
            "vahşi",
            "dini",
            "kişisel",
            "Günlük Makyaj",
            "Porselen Makyaj",
            "Show Makyajı",
            "Kalıcı Makyaj",
            "Gece Makyajı",
            "cilt bakımı",
            'Mühendislik',
            "Tıp",
            "Fen edebiyat",
            "İktisadi ve idari bilimleri",
            "Eğitim",
            "Diş hekimliği",
            "Mimarlık",
            "İslahiye iktisadi ve idari bilimleri",
            "Güzel sanatlar",
            "Sağlık bilimleri",
            "Hukuk",
            "İlahiyat",
            "İletişim",
            "Havacılık ve uzay mühendisliği",
            "Turizm",
            "grand theft auto",
            "counter strike global offensive",
            "euro truck simulator",
            "minecraft",
            "fifa",
            "battlefield",
            "call of duty",
            "prey",
            "watch dogs",
            "fallout",
            "far cry",
            "half-life",
            "assassin's creed",
            "league of legends",
            "destiny",
            "rise of the tomb raider",
            "clash of clans",
            "adana",
            "adıyaman",
            "afyon",
            "ağrı",
            "amasya",
            "ankara",
            "antalya",
            "artvin",
            "aydın",
            "balıkesir",
            "bilecik",
            "bingöl",
            "bitlis",
            "bolu",
            "burdur",
            "bursa",
            "çanakkale",
            "çankırı",
            "çorum",
            "denizli",
            "diyarbakır",
            "edirne",
            "elazığ",
            "erzincan",
            "erzurum",
            "eskişehir",
            "gaziantep",
            "giresun",
            "gümüşhane",
            "hakkari",
            "hatay",
            "ısparta",
            "mersin",
            "istanbul",
            "izmir",
            "kars",
            "kastamonu",
            "kayseri",
            "Kırklareli",
            "kırşehir",
            "kocaeli",
            "konya",
            "kütahya",
            "malatya",
            "manisa",
            "kahramanmaraş",
            "mardin",
            "muğla",
            "muş",
            "nevşehir",
            "niğde",
            "ordu",
            "rize",
            "sakarya",
            "samsun",
            "siirt",
            "sinop",
            "sivas",
            "tekirdağ",
            "tokat",
            "trabzon",
            "tunceli",
            "şanlıurfa",
            "uşak",
            "van",
            "yozgat",
            "zonguldak",
            "aksaray",
            "bayburt",
            "karaman",
            "kırıkkale",
            "batman",
            "şırnak",
            "bartın",
            "ardahan",
            "ığdır",
            "yalova",
            "karabuk",
            "kilis",
            "osmaniye",
            "düzce",
            "yazlık",
            "kışlık",
            "mevsimlik",
            "aksesuar"
        ]
        return all_

class Category2:
    def muhendislik():
        en = [ # mühendislik dalları
            "Makine",
            "Elektrik ve elektronik",
            "Gıda",
            "Fizik",
            "İnşaat",
            "Tekstil",
            "Endüstri",
            "Bigisayar",
            "Yazılım",
            "Metalurji ve malzeme",
            "Enerji sistemleri",
            "Biyoproses ve kimya",
            "Optik ve akustik",
        ]
        return en

    def tp():
        me = [ # tıpın dalları
            "Dahili tıp birimleri",
            "Cerrahi tıp birimleri",
            "Temel tıp birimleri",
        ]
        return me

    def fen_edebiyat():
        sl = [ # fen edebiyat
            "Tarih",
            "Matematik",
            "Türk dili ve edebiyat",
            "Biyoloji",
            "Batı dilleri ve edebiyat",
            "Kimya",
            "Arkeoloji",
            "Sosyoloji",
            "Kültür varlıklarını koruma ve onarım",
            "İstatislik",
            "Psikoloji",
            "Çoğrafya",
            "Felsefe",
            "Doğu dilleri ve edebiyatı",
        ]
        return sl
    
    def iktisadi_ve_idari_bilimleri():
        eaas = [ # iktisadi ve  idari
            "İktisat",
            "İşletme",
            "Uluslar arası ticaret ve lojistik",
            "Kamu yönetim",
            "Maliye",
            "Küresel siyaset ve uluslararası ilişkiler",
        ]
        return eaas

    def egitim():
        ed = [ # eğitim
            "Matematik ve fen bilimleri",
            "Güzel sanatlar",
            "Türkçe ve sosyal bilimler",
            "Yabancı diller",
            "Eğitim yönetimi anabilim dalı",
            "Eğitim programları ve öğretim adabilim dalı",
            "Rehberlik ve psikojik danışma anabilim dalı",
            "Eğitimin felsefesi,sosyal ve tarihi temelleri anabilim dalı",
            "Hayat boyu öğrenme ve yetişkin eğitimi anabilim dalı",
            "Öğretim teknolojileri anabilim dalı",
            "Eğitimde ölçme ve değerlendirme anabilim dalı",
            "Bilgisayar ve öğretim teknolojileri",
            "Okul öncesi eğitimi anabilim dalı",
            "Sınıf eğitimi anabilim dalı",
            "Özel yetenekliler eğitimi anabilim dalı",
            "Zihinsel engelliler eğitimi anabilim dalı",
            "Görme engelliler eğitimi anabilim dalı",
            "İşitme engelliler eğitimi anabilim dalı",
            "eğitimi anabilim dalı",
        ]
        return ed

    def dis_hekimligi():
        de = [ # diş 
            "Ağız Diş ve Çene Cerrahisi AD.",
            "Endodonti AD.",
            "Oral Diagnoz ve Radyoloji AD.",
            "Ortodonti AD.",
            "Pedodonti AD.",
            "Periodontoloji AD.",
            "Protetik Diş Tedavisi AD.",
            "Restoratif Diş Tedavisi AD.",
        ]
        return de

    def mimarlk():
        arc = [ # mimar
            "ŞEHİR VE BÖLGE PLANLAMA BÖLÜMÜ",
            "ENDÜSTRİ ÜRÜNLERİ TASARIMI BÖLÜMÜ",
            "MİMARLIK BÖLÜMÜ",
            "İÇ MİMARLIK BÖLÜMÜ",
        ]
        return arc

    def islahiye_iktisadi_ve_idari_bilimleri():
        ieaas = [ # İslahiye İktisadi ve İdari Bilimler Fakültesi
            "EKONOMETRİ",
            "ULUSLARARASI İLİŞKİLER",
            "MALİYE",
            "KAMU YÖNETİMİ",
            "İKTİSAT",
            "İŞLETME",
        ]
        return ieaas

    def guzel_sanatlar():
        fi = [ # güzel sanatlar
            "GASTRONOMİ VE MUTFAK SANATLARI BÖLÜMÜ",
            "MODA VE TEKSTİL TASARIMI BÖLÜMÜ",
            "SAHNE VE GÖSTERİ SANATLARI BÖLÜMÜ",
            "GELENEKSEL TÜRK EL SANATLARI BÖLÜMÜ",
            "SİNEMA VE TELEVİZYON BÖLÜMÜ",
            "FOTOĞRAF BÖLÜMÜ",
            "SERAMİK VE CAM BÖLÜMÜ",
            "RESİM BÖLÜMÜ",
            "HEYKEL BÖLÜMÜ",
            "GRAFİK BÖLÜMÜ",
        ]
        return fi

    def saglk_bilimleri():
        he = [ #sağlık
            "FİZYOTERAPİ VE REHABİLİTASYON",
            "DİL VE KONUŞMA TERAPİSİ",
            "ODYOLOJİ",
            "BESLENME VE DİYETETİK",
            "SAĞLIK YÖNETİMİ",
            "SOLUNUM TERAPİSTLİĞİ",
            "EBELİK",
            "HEMŞİRELİK",
        ]
        return he

    def hukuk():
        la = [ # hukuk 
            "HUKUK FAKÜLTESİ", 
            "ANAYASA HUKUKU ANABİLİM DALI", 
            "CEZA VE CEZA MUHAKEMESİ HUKUKU ANABİLİM DALI", 
            "GENEL KAMU HUKUKU ANABİLİM DALI", 
            "HUKUK FELSEFESİ VE SOSYOLOJİSİ ANABİLİM DALI", 
            "HUKUK TARİHİ ANABİLİM DALI", 
            "MALİ HUKUK ANABİLİM DALI", 
            "MİLLETLERARASI HUKUK ANABİLİM DALI", 
            "İDARE HUKUKU ANABİLİM DALI", 
            "İNSAN HAKLARI ANABİLİM DALI", 
            "İSLAM HUKUKU ANABİLİM DALI", 
            "TİCARET HUKUKU ANABİLİM DALI", 
            "AVRUPA BİRLİĞİ HUKUKU ANABİLİM DALI", 
            "DENİZ HUKUKU ANABİLİM DALI", 
            "KARŞILAŞTIRMALI HUKUK ANABİLİM DALI", 
            "MEDENİ HUKUK ANABİLİM DALI", 
            "MEDENİ USUL VE İCRA İFLAS HUKUKU ANABİLİM DALI",
            "MİLLETLERARASI ÖZEL HUKUK ANABİLİM DALI", 
            "ROMA HUKUKU ANABİLİM DALI", 
            "İŞ VE SOSYAL GÜVENLİK HUKUKU ANABİLİM DALI",
        ]
        return la

    def ilahiyat():
        th = [ # ilahiyat
            "Tefsir",
            "Hadis",
            "Kelam",
            "İslam Hukuku",
            "İslam Mezhepleri Tarihi",
            "Tasavvuf",
            "Arap Dili ve Belagatı",
            "Kuranı Kerim Okuma ve Kıraat İlmi",
            "Din Eğitimi",
            "Dinler Tarihi",
            "İslam Felsefesi",
            "Din Sosyolojisi",
            "Din Psikolojisi",
            "Felsefe Tarihi",
            "Mantık",
            "İslam Tarihi",
            "Türk İslam Edebiyatı",
            "Türk İslam Sanatları Tarihi",
            "Türk Din Musikisi",
        ]
        return th

    def iletisim():
        co = [ # iletişim
            "Gazetecilik",
            "Halkla ilişkiler ve tanıtım",
            "Radyo, tv ve sinema",
            "İletişim enformatiği",
            "Reklamcılık",
        ]
        return co

    def havaclk_ve_uzay_mühendisligi():
        ae = [ # HAVACILIK VE UZAY BİLİMLERİ FAKÜLTESİ
            "HAVACILIK YÖNETİMİ BÖLÜMÜ",
            "UÇAK VE UZAY MÜHENDİSLİĞİ BÖLÜMÜ",
            "PİLOTAJ BÖLÜMÜ",
        ]
        return ae
    def all():
        all_ = [
            "Makine",
            "Elektrik ve elektronik",
            "Gıda",
            "Fizik",
            "İnşaat",
            "Tekstil",
            "Endüstri",
            "Bigisayar",
            "Yazılım",
            "Metalurji ve malzeme",
            "Enerji sistemleri",
            "Biyoproses ve kimya",
            "Optik ve akustik",
            "Dahili tıp birimleri",
            "Cerrahi tıp birimleri",
            "Temel tıp birimleri",
            "Tarih",
            "Matematik",
            "Türk dili ve edebiyat",
            "Biyoloji",
            "Batı dilleri ve edebiyat",
            "Kimya",
            "Arkeoloji",
            "Sosyoloji",
            "Kültür varlıklarını koruma ve onarım",
            "İstatislik",
            "Psikoloji",
            "Çoğrafya",
            "Felsefe",
            "Doğu dilleri ve edebiyatı",
            "İktisat",
            "İşletme",
            "Uluslar arası ticaret ve lojistik",
            "Kamu yönetim",
            "Maliye",
            "Küresel siyaset ve uluslararası ilişkiler",
            "Matematik ve fen bilimleri",
            "Güzel sanatlar",
            "Türkçe ve sosyal bilimler",
            "Yabancı diller",
            "Eğitim yönetimi anabilim dalı",
            "Eğitim programları ve öğretim adabilim dalı",
            "Rehberlik ve psikojik danışma anabilim dalı",
            "Eğitimin felsefesi,sosyal ve tarihi temelleri anabilim dalı",
            "Hayat boyu öğrenme ve yetişkin eğitimi anabilim dalı",
            "Öğretim teknolojileri anabilim dalı",
            "Eğitimde ölçme ve değerlendirme anabilim dalı",
            "Bilgisayar ve öğretim teknolojileri",
            "Okul öncesi eğitimi anabilim dalı",
            "Sınıf eğitimi anabilim dalı",
            "Özel yetenekliler eğitimi anabilim dalı",
            "Zihinsel engelliler eğitimi anabilim dalı",
            "Görme engelliler eğitimi anabilim dalı",
            "İşitme engelliler eğitimi anabilim dalı",
            "eğitimi anabilim dalı",
            "Ağız Diş ve Çene Cerrahisi AD.",
            "Endodonti AD.",
            "Oral Diagnoz ve Radyoloji AD.",
            "Ortodonti AD.",
            "Pedodonti AD.",
            "Periodontoloji AD.",
            "Protetik Diş Tedavisi AD.",
            "Restoratif Diş Tedavisi AD.",
            "ŞEHİR VE BÖLGE PLANLAMA BÖLÜMÜ",
            "ENDÜSTRİ ÜRÜNLERİ TASARIMI BÖLÜMÜ",
            "MİMARLIK BÖLÜMÜ",
            "İÇ MİMARLIK BÖLÜMÜ",
            "EKONOMETRİ",
            "ULUSLARARASI İLİŞKİLER",
            "MALİYE",
            "KAMU YÖNETİMİ",
            "İKTİSAT",
            "İŞLETME",
            "GASTRONOMİ VE MUTFAK SANATLARI BÖLÜMÜ",
            "MODA VE TEKSTİL TASARIMI BÖLÜMÜ",
            "SAHNE VE GÖSTERİ SANATLARI BÖLÜMÜ",
            "GELENEKSEL TÜRK EL SANATLARI BÖLÜMÜ",
            "SİNEMA VE TELEVİZYON BÖLÜMÜ",
            "FOTOĞRAF BÖLÜMÜ",
            "SERAMİK VE CAM BÖLÜMÜ",
            "RESİM BÖLÜMÜ",
            "HEYKEL BÖLÜMÜ",
            "GRAFİK BÖLÜMÜ",
            "FİZYOTERAPİ VE REHABİLİTASYON",
            "DİL VE KONUŞMA TERAPİSİ",
            "ODYOLOJİ",
            "BESLENME VE DİYETETİK",
            "SAĞLIK YÖNETİMİ",
            "SOLUNUM TERAPİSTLİĞİ",
            "EBELİK",
            "HEMŞİRELİK",
            "HUKUK FAKÜLTESİ", 
            "ANAYASA HUKUKU ANABİLİM DALI", 
            "CEZA VE CEZA MUHAKEMESİ HUKUKU ANABİLİM DALI", 
            "GENEL KAMU HUKUKU ANABİLİM DALI", 
            "HUKUK FELSEFESİ VE SOSYOLOJİSİ ANABİLİM DALI", 
            "HUKUK TARİHİ ANABİLİM DALI", 
            "MALİ HUKUK ANABİLİM DALI", 
            "MİLLETLERARASI HUKUK ANABİLİM DALI", 
            "İDARE HUKUKU ANABİLİM DALI", 
            "İNSAN HAKLARI ANABİLİM DALI", 
            "İSLAM HUKUKU ANABİLİM DALI", 
            "TİCARET HUKUKU ANABİLİM DALI", 
            "AVRUPA BİRLİĞİ HUKUKU ANABİLİM DALI", 
            "DENİZ HUKUKU ANABİLİM DALI", 
            "KARŞILAŞTIRMALI HUKUK ANABİLİM DALI", 
            "MEDENİ HUKUK ANABİLİM DALI", 
            "MEDENİ USUL VE İCRA İFLAS HUKUKU ANABİLİM DALI",
            "MİLLETLERARASI ÖZEL HUKUK ANABİLİM DALI", 
            "ROMA HUKUKU ANABİLİM DALI", 
            "İŞ VE SOSYAL GÜVENLİK HUKUKU ANABİLİM DALI",
            "Tefsir",
            "Hadis",
            "Kelam",
            "İslam Hukuku",
            "İslam Mezhepleri Tarihi",
            "Tasavvuf",
            "Arap Dili ve Belagatı",
            "Kuranı Kerim Okuma ve Kıraat İlmi",
            "Din Eğitimi",
            "Dinler Tarihi",
            "İslam Felsefesi",
            "Din Sosyolojisi",
            "Din Psikolojisi",
            "Felsefe Tarihi",
            "Mantık",
            "İslam Tarihi",
            "Türk İslam Edebiyatı",
            "Türk İslam Sanatları Tarihi",
            "Türk Din Musikisi",
            "Gazetecilik",
            "Halkla ilişkiler ve tanıtım",
            "Radyo, tv ve sinema",
            "İletişim enformatiği",
            "Reklamcılık",
            "HAVACILIK YÖNETİMİ BÖLÜMÜ",
            "UÇAK VE UZAY MÜHENDİSLİĞİ BÖLÜMÜ",
            "PİLOTAJ BÖLÜMÜ",
        ]
        return all_


def university():
    uni = (
        'Abant İzzet Baysal Üniversitesi',
        'Abdullah Gül Üniversitesi',
        'Adana Bilim ve Teknoloji Üniversitesi',
        'Adıyaman Üniversitesi',
        'Adnan Menderes Üniversitesi',
        'Afyon Kocatepe Üniversitesi',
        'Ağrı İbrahim Çeçen Üniversitesi',
        'Ahi Evran Üniversitesi',
        'Akdeniz Üniversitesi',
        'Aksaray Üniversitesi',
        'Alanya Alaaddin Keykubat Üniversitesi',
        'Amasya Üniversitesi',
        'Anadolu Üniversitesi',
        'Ankara Üniversitesi',
        'Ankara Sosyal Bilimler Üniversitesi',
        'Ardahan Üniversitesi',
        'Artvin Çoruh Üniversitesi',
        'Atatürk Üniversitesi',
        'Balıkesir Üniversitesi',
        'Bandırma Onyedi Eylül Üniversitesi',
        'Bartın Üniversitesi',
        'Batman Üniversitesi',
        'Bayburt Üniversitesi',
        'Bilecik Şeyh Edebali Üniversitesi',
        'Bingöl Üniversitesi',
        'Bitlis Eren Üniversitesi',
        'Boğaziçi Üniversitesi',
        'Bozok Üniversitesi',
        'Bursa Teknik Üniversitesi',
        'Devlet Üniversitesi',
        'Celal Bayar Üniversitesi',
        'Cumhuriyet Üniversitesi',
        'Çanakkale Onsekiz Mart Üniversitesi',
        'Çankırı Karatekin Üniversitesi',
        'Çukurova Üniversitesi',
        'Dicle Üniversitesi',
        'Dokuz Eylül Üniversitesi',
        'Dumlupınar Üniversitesi',
        'Düzce Üniversitesi',
        'Ege Üniversitesi',
        'Erciyes Üniversitesi',
        'Erzincan Üniversitesi',
        'Erzurum Teknik Üniversitesi',
        'Eskişehir Osmangazi Üniversitesi',
        'Fırat Üniversitesi',
        'Galatasaray Üniversitesi',
        'Gazi Üniversitesi',
        'Gaziantep Üniversitesi',
        'Gaziosmanpaşa Üniversitesi',
        'Gebze Teknik Üniversitesi',
        'Giresun Üniversitesi',
        'Gümüşhane Üniversitesi',
        'Hacettepe Üniversitesi',
        'Hakkari Üniversitesi',
        'Harran Üniversitesi',
        'Hitit Üniversitesi',
        'Iğdır Üniversitesi',
        'İnönü Üniversitesi',
        'İskenderun Teknik Üniversitesi',
        'İstanbul Medeniyet Üniversitesi',
        'İstanbul Üniversitesi',
        'İstanbul Teknik Üniversitesi',
        'İzmir Kâtip Çelebi Üniversitesi',
        'Kafkas Üniversitesi',
        'Kahramanmaraş Sütçü İmam Üniversitesi',
        'Karabük Üniversitesi',
        'Karadeniz Teknik Üniversitesi',
        'Karamanoğlu Mehmetbey Üniversitesi',
        'Kastamonu Üniversitesi',
        'Kırıkkale Üniversitesi',
        'Kırklareli Üniversitesi',
        'Kilis 7 Aralık Üniversitesi',
        'Kocaeli Üniversitesi',
        'Necmettin Erbakan Üniversitesi',
        'Devlet Üniversitesi',
        'Mardin Artuklu Üniversitesi',
        'Marmara Üniversitesi',
        'Mehmet Akif Ersoy Üniversitesi',
        'Mersin Üniversitesi',
        'Mimar Sinan Güzel Sanatlar Üniversitesi',
        'Muğla Sıtkı Koçman Üniversitesi',
        'Mustafa Kemal Üniversitesi',
        'Muş Alparslan Üniversitesi',
        'Namık Kemal Üniversitesi',
        'Nevşehir Hacı Bektaş Veli Üniversitesi',
        'Niğde Üniversitesi',
        'Ondokuz Mayıs Üniversitesi',
        'Ordu Üniversitesi',
        'Orta Doğu Teknik Üniversitesi',
        'Osmaniye Korkut Ata Üniversitesi',
        'Pamukkale Üniversitesi',
        'Recep Tayyip Erdoğan Üniversitesi',
        'Sakarya Üniversitesi',
        'Selçuk Üniversitesi',
        'Siirt Üniversitesi',
        'Sinop Üniversitesi',
        'Süleyman Demirel Üniversitesi',
        'Şırnak Üniversitesi',
        'Trakya Üniversitesi',
        'Tunceli Üniversitesi',
        'Türk Alman Üniversitesi',
        'Türkiye Sağlık Bilimleri Üniversitesi',
        'Türkiye Uluslararası İslam, Bilim ve Teknoloji Üniversitesi',
        'Uludağ Üniversitesi',
        'Uşak Üniversitesi',
        'Yalova Üniversitesi',
        'Yıldız Teknik Üniversitesi',
        'Yıldırım Beyazıt Üniversitesi',
        'Yüzüncü Yıl Üniversitesi',
        'Bülent Ecevit Üniversitesi',
        'Acıbadem Üniversitesi',
        'Akev Üniversitesi',
        'Alanya Hamdullah Emin Paşa Üniversitesi',
        'Atılım Üniversitesi',
        'Avrasya Üniversitesi',
        'Bahçeşehir Üniversitesi',
        'Başkent Üniversitesi',
        'Beykent Üniversitesi',
        'Bezmiâlem Vakıf Üniversitesi',
        'Bilkent Üniversitesi',
        'Biruni Üniversitesi',
        'Bursa Orhangazi Üniversitesi',
        'Canik Başarı Üniversitesi',
        'Çankaya Üniversitesi',
        'Çağ Üniversitesi',
        'Doğuş Üniversitesi',
        'Fatih Sultan Mehmet Üniversitesi',
        'Fatih Üniversitesi',
        'Gedik Üniversitesi',
        'Gediz Üniversitesi',
        'Haliç Üniversitesi',
        'Hasan Kalyoncu Üniversitesi',
        'Işık Üniversitesi',
        'İbn-u Haldun Üniversitesi',
        'İpek Üniversitesi',
        'İstanbul 29 Mayıs Üniversitesi',
        'İstanbul Arel Üniversitesi',
        'İstanbul Aydın Üniversitesi',
        'İstanbul Bilgi Üniversitesi',
        'İstanbul Bilim Üniversitesi',
        'İstanbul Esenyurt Üniversitesi',
        'İstanbul Gelişim Üniversitesi',
        'İstanbul Kemerburgaz Üniversitesi',
        'İstanbul Kültür Üniversitesi',
        'İstanbul Medipol Üniversitesi',
        'İstanbul Rumeli Üniversitesi',
        'İstanbul Sabahattin Zaim Üniversitesi',
        'İstanbul Şehir Üniversitesi',
        'İstanbul Ticaret Üniversitesi',
        'İstinye Üniversitesi',
        'İzmir Ekonomi Üniversitesi',
        'İzmir Üniversitesi',
        'Kadir Has Üniversitesi',
        'Karatay Üniversitesi',
        'Koç Üniversitesi',
        'Konya Gıda Tarım Üniversitesi',
        'Maltepe Üniversitesi',
        'MEF Üniversitesi',
        'Melikşah Üniversitesi',
        'Mevlana Üniversitesi',
        'Murat Hüdavendigar Üniversitesi',
        'Nişantaşı Üniversitesi',
        'Nuh Naci Yazgan Üniversitesi',
        'Okan Üniversitesi',
        'Özyeğin Üniversitesi',
        'Piri Reis Üniversitesi',
        'Sabancı Üniversitesi',
        'Sanko Üniversitesi',
        'Selahattin Eyyubi Üniversitesi',
        'Süleyman Şah Üniversitesi',
        'Şifa Üniversitesi',
        'TED Üniversitesi',
        'TOBB Ekonomi ve Teknoloji Üniversitesi',
        'Toros Üniversitesi',
        'Turgut Özal Üniversitesi',
        'Türk Hava Kurumu Üniversitesi',
        'Ufuk Üniversitesi',
        'Uluslararası Antalya Üniversitesi',
        'Üsküdar Üniversitesi',
        'Yaşar Üniversitesi',
        'Yeditepe Üniversitesi',
        'Yeni Yüzyıl Üniversitesi',
        'Yüksek İhtisas Üniversitesi',
        'Zirve Üniversitesi',
        'Kanuni Üniversitesi',
    )
    return uni
def jop():
    jo = (
        "Öğrenci",
        'Acentacı',
        'Acil durum yönetmeni',
        'Adli tabip',
        'Agronomist',
        'Ağ yöneticisi',
        'Aşçı',
        'Aşçıbaşı',
        'Ahşap tekne yapımcısı',
        'Aile hekimi',
        'Aktar',
        'Akortçu',
        'Aktör',
        'Aktüer',
        'Aktris',
        'Akustikçi',
        'Albay',
        'Ambalajcı',
        'Ambarcı',
        'Ambulans şoförü',
        'Amiral',
        'Anahtarcı',
        'Analist',
        'Anestezi uzmanı',
        'Anestezi Teknikeri',
        'Animatör',
        'Antika satıcısı',
        'Antropolog',
        'Apartman yöneticisi',
        'Araba satıcısı',
        'Araba yıkayıcısı',
        'Arabacı',
        'Arabulucu',
        'Araştırmacı',
        'Arıcı',
        'Arkeolog',
        'Armatör',
        'Arpist',
        'Arşivci',
        'Artist',
        'Asansörcü',
        'Asistan',
        'Asker',
        'Astrofizikçi',
        'Astrolog',
        'Astronom',
        'Astronot',
        'Astsubay',
        'Atlet',
        'Av bekçisi',
        'Avcı',
        'Avizeci',
        'Avukat',
        'Ayakçı (otogar, lokanta)',
        'Ayakkabı boyacısı',
        'Ayakkabı tamircisi',
        'Ayakkabıcı',
        'Ayı oynatıcısı',
        'Araba tamircisi',
        'Bacacı',
        'Badanacı',
        'Baharatçı',
        'Bahçe bitkileri uzmanı',
        'Bahçıvan',
        'Bakan',
        'Bakıcı',
        'Bakırcı',
        'Bakkal',
        'Bakteriyolog',
        'Balıkçı',
        'Balon pilotu',
        'Bankacı',
        'Banker',
        'Barmen',
        'Barmeyd',
        'Basketbolcu',
        'Başbakan',
        'Başçavuş',
        'Başdümenci',
        'Başhemşire',
        'Başkan',
        'Başkomiser',
        'Başpiskopos',
        'Başrahip',
        'Belediye başkanı',
        'Belediye meclisi üyesi',
        'Benzinci',
        'Berber',
        'Besteci',
        'Biletçi',
        'Bilgisayar mühendisi',
        'Bilgisayar programcısı',
        'Bilgisayar tamircisi',
        'Bilimadamı',
        'Bilirkişi',
        'Binicilik',
        'Biracı',
        'Bisikletçi',
        'Biyografi yazarı',
        'Biyolog',
        'Bobinajcı',
        'Bombacı',
        'Bomba imhacı',
        'Borsacı',
        'Borucu',
        'Botanikçi',
        'Boyacı',
        'Bozacı',
        'Böcekbilimci',
        'Börekçi',
        'Bulaşıkçı',
        'Buldozer operatörü',
        'Bütçe uzmanı',
        'Büyükelçi',
        'Besicilik',
        'Bebek Bakıcısı',
        'Bilgi İşlemci',
        'Camcı',
        'Cerrah',
        'Celep',
        'Cellat',
        'Cost Control',
        'Cillopçu',
        'Cumhurbaşkanı',
        'Çamaşırcı',
        'Çantacı',
        'Çarkçı',
        'Çatıcı',
        'Çaycı',
        'Çevirmen',
        'Çevrebilimci',
        'Çevre Mühendisi',
        'Çeyizci',
        'Çıkıkçı',
        'Çıkrıkçı',
        'Çiçekçi',
        'Çiftçi',
        'Çiftlik işletici',
        'Çikolatacı',
        'Çilingir',
        'Çinici',
        'Çitçi',
        'Çoban',
        'Çocuk doktoru',
        'Çorapçı',
        'Çöp işçisi',
        'Çöpçü',
        'Çırak',
        'Çevik Kuvvet',
        'Dadı',
        'Daktilograf',
        'Dalgıç',
        'Damıtıcı',
        'Danışman',
        'Dansöz',
        'Davulcu',
        'Debbağ',
        'Dedektif',
        'Değirmen işçisi',
        'Değirmenci',
        'Demirci',
        'Demiryolu işçisi',
        'Denetçi',
        'Denetleyici',
        'Denizci',
        'Depocu',
        'Derici',
        'Desinatör',
        'Devlet memuru',
        'Dilci',
        'Dilenci',
        'Diplomat',
        'Diş hekimi',
        'Diyetisyen',
        'Dizgici',
        'Doğalgazcı',
        'Doğramacı',
        'Doğum uzmanı',
        'Dok işçisi',
        'Dokumacı',
        'Doktor',
        'Dondurmacı',
        'Dökümcü',
        'Döşemeci',
        'Dövizci',
        'Dublajcı',
        'Duvarcı',
        'Dümenci',
        'diş teknisyeni',
        'Ebe(kadın doğum)',
        'Eczacı',
        'Eczacı kalfası',
        'Editör',
        'Eğitimci',
        'Eğitmen',
        'Ekonomist',
        'Elektrik mühendisi',
        'Elektronik mühendisi',
        'Elektrikçi',
        'Eleştirmen',
        'Embriyolog',
        'Emlakçı',
        'Emniyet amiri',
        'Emniyet genel müdürü',
        'Endüstri mühendisi',
        'Endüstri sistemleri mühendisi',
        'Enstrüman imalatçısı',
        'Ergonomist',
        'Eskici',
        'Estetisyen',
        'Etolojist',
        'Etimolog',
        'Etnolog',
        'Ev hanımı',
        'Fabrika işçisi',
        'Fahişe',
        'Falcı',
        'Fermantasyon işçisi',
        'Fıçıcı',
        'Fırıncı',
        'Figüran',
        'Film yapımcısı',
        'Film yönetmeni',
        'Filozof',
        'Finansör',
        'Fizikçi',
        'Fizyonomist',
        'Fizyoterapist',
        'Acil tıp teknisyeni',
        'Fon yöneticisi',
        'Forklift operatörü',
        'Fotoğrafçı',
        'Futbolcu',
        'Gardiyan',
        'Galerici',
        'Garson',
        'Gazete dağıtıcısı',
        'Gazete satıcısı',
        'Gazeteci',
        'Gelir uzmanı',
        'Gelir uzman yardımcısı',
        'Gemici',
        'General',
        'Genetik mühendisi',
        'Geyşa',
        'Gezgin',
        'Gezici vaiz',
        'Gıda mühendisi',
        'Gitarist',
        'Gondolcu',
        'Gökbilimci',
        'Göz doktoru',
        'Gözetmen',
        'Gözlükçü',
        'Grafiker',
        'Gramer uzmanı',
        'Greyder operatörü',
        'Guru',
        'Güfteci',
        'Gümrük memuru',
        'Gümrük müşaviri',
        'Gümrük müşavir yardımcısı',
        'Gümrük uzmanı',
        'Gündelikçi',
        'Güzellik uzmanı',
        'Haberci',
        'Haddeci',
        'Haham',
        'Hakem',
        'Halıcı',
        'Halkbilimci',
        'Hamal',
        'Hamamcı',
        'Hamurkâr',
        'Hareket memuru',
        'Haritacı',
        'Harita mühendisi',
        'Hastabakıcı',
        'Hattat',
        'Hava trafikçisi',
        'Havacı',
        'Haydut',
        'Hayvan bakıcısı',
        'Hayvan terbiyecisi',
        'Hemşire',
        'Hesap uzmanı',
        'Heykeltıraş',
        'Hırdavatçı',
        'Hırsız',
        'Hidrolikçi',
        'Hizmetçi',
        'Hokkabaz',
        'Host',
        'Hostes',
        'Hukukçu',
        'Hurdacı',
        'Irgat',
        'Işıkçı',
        'İcra memuru',
        'İç mimar',
        'İğneci',
        'İhracatçı',
        'İktisatçı',
        'İlahiyatçı',
        'İllüzyonist',
        'İmam',
        'İnsan kaynakları uzmanı',
        'İnşaat mühendisi',
        'İnşaatçı',
        'İpçi',
        'İplikçi',
        'İstatistikçi',
        'İstihkâmcı',
        'İşaretçi',
        'İşçi',
        'İşletmeci',
        'İşletme mühendisi',
        'İşportacı',
        'İş ve uğraşı terapisti',
        'İtfaiyeci',
        'İthalatçı',
        'Jeofizik mühendisi',
        'Jeoloji mühendisi',
        'Jeolog',
        'Jeomorfolog',
        'Jinekolog',
        'Jimnastikçi',
        'Jokey',
        'Kabin görevlisi',
        'Kabuk soyucusu',
        'Kadın berberi',
        'Kadın terzisi',
        'Kâğıtçı',
        'Kahveci',
        'Kâhya',
        'Kalaycı',
        'Kalıpçı',
        'Kaloriferci',
        'Kamarot',
        'Kameraman',
        'Kamyoncu',
        'Kapı satıcısı',
        'Kapıcı',
        'Kaplamacı',
        'Kaportacı',
        'Kaptan',
        'Kardinal',
        'Kardiyolog',
        'Karikatürist',
        'Karoserci',
        'Karpuzcu',
        'Kasap',
        'Kasiyer',
        'Kat görevlisi',
        'Kâtip',
        'Kayıkçı',
        'Kaymakam',
        'Kaynakçı',
        'Kazıcı',
        'Kebapçı',
        'Kemancı',
        'Kesimci',
        'Kırtasiyeci',
        'Kimyager',
        'Kimya mühendisi',
        'Kitapçı',
        'Klarnetçi',
        'Koleksiyoncu',
        'Komedyen',
        'Komisyoncu',
        'Komiser',
        'Konserveci',
        'Konsolos',
        'Konsomatris',
        'Kontrolör',
        'Konveyör operatörü',
        'Kopyalayıcı',
        'Koreograf',
        'Korgeneral',
        'Koramiral',
        'Korsan',
        'Koruma görevlisi',
        'Komiser',
        'Komiser yardımcısı',
        'Kozmolog',
        'Köfteci',
        'Kömürcü',
        'Köpek eğiticisi',
        'Köşe yazarı',
        'Kuaför',
        'Kuşçu',
        'Kumarbaz',
        'Kumaşçı',
        'Kumcu',
        'Kuru temizlemeci',
        'Kuruyemişçi',
        'Kurye',
        'Kuşbilimci',
        'Kuyumcu',
        'Kürkçü',
        'Kütüphaneci',
        'Laborant',
        'Laboratuar işçisi',
        'Lahmacuncu',
        'Lehimci',
        'Levazımcı',
        'Lobici',
        'Lokantacı',
        'Lokomotifçi',
        'Lostromo',
        'Lostracı',
        'Lokman',
        'Madenci',
        'Makasçı',
        'Makastar',
        'Maketçi',
        'Makinist',
        'Makine mühendisi',
        'Makine zabiti',
        'Makyajcı',
        'Mali hizmetler uzmanı',
        'Manastır baş rahibesi',
        'Manav',
        'Manifaturacı',
        'Manikürcü',
        'Manken',
        'Marangoz',
        'Masör',
        'Masöz',
        'Matador',
        'Matbaacı',
        'Matematikçi',
        'Matkapçı',
        'Memur',
        'Menajer',
        'Mermerci',
        'Metalurji mühendisi',
        'Meteoroloji uzmanı',
        'Metin yazarı',
        'Mevsimlik işçi',
        'Meydancı',
        'Meyhaneci',
        'Mezarcı',
        'Midyeci',
        'Mikrobiyolog',
        'Milletvekili',
        'Mimar',
        'Misyoner',
        'Mobilyacı',
        'Modacı',
        'Model',
        'Modelci',
        'Modelist',
        'Montajcı',
        'Montör',
        'Motor tamircisi',
        'Motorcu',
        'Muallim',
        'Muhabbet tellalı',
        'Muhabir',
        'Muhafız',
        'Muhasebeci',
        'Muhtar',
        'Mumyalayıcı',
        'Muzcu',
        'Mübaşir',
        'Müdür',
        'Müezzin',
        'Müfettiş',
        'Müşavir',
        'Mühendis',
        'Müneccim',
        'Mürebbiye',
        'Müsteşar',
        'Müteahhit',
        'Mütercim',
        'Müze müdürü',
        'Müzik yönetmeni',
        'Müzisyen',
        'Nalıncı',
        'Nakışçı',
        'Nakliyeci',
        'Nalbant',
        'Nalbur',
        'Noter',
        'Obuacı',
        'Ocakçı',
        'Odacı',
        'Oduncu',
        'Okçu',
        'Okul müdürü',
        'Okutman',
        'Operatör',
        'Opera sanatçısı',
        'Orgcu',
        'Orgeneral',
        'Orman mühendisi',
        'Ornitolog (veya kuşbilimci)',
        'Otelci',
        'Oto elektrikçisi',
        'Oto tamircisi',
        'Oto yedek parçacı',
        'Overlokçu',
        'Oymacı',
        'Oyuncu',
        'Oyun hostesi',
        'Oyun yazarı',
        'Oyuncakçı',
        'Oto lastik tamircisi',
        'Öğretmen',
        'Öğretim elemanı',
        'Öğretim görevlisi',
        'Öğretim üyesi',
        'Örmeci',
        'Ön muhasebeci',
        'Ön muhasebe sorumlusu',
        'Ön muhasebe yardımcı elemanı',
        'Ön büro elemanı',
        'Özel şoför',
        'Paketleyici',
        'Palyaço',
        'Pandomimci',
        'Pansiyoncu',
        'Pansumancı',
        'Papa',
        'Papaz',
        'Paralı asker',
        'Park bekçisi',
        'Pastörizör',
        'Patolog',
        'Peçeteci',
        'Pencereci',
        'Perukçu',
        'Peyzaj mimarı',
        'Peyzaj teknikeri',
        'Pideci',
        'Pilavcı',
        'Pilot',
        'Piskopos',
        'Piyade',
        'Piyango satıcısı',
        'Piyanist',
        'Polis memuru',
        'Polis şefi',
        'Polisajcı',
        'Politikacı',
        'Pompacı',
        'Postacı',
        'Profesör',
        'Proktolog',
        'Protokol görevlisi',
        'Psikiyatr',
        'Psikolog',
        'Psikolojik danışmanlık ve rehberlik',
        'Paramedik',
        'Radyolog',
        'Redaktör',
        'Rehber',
        'Rejisör',
        'Reklamcı',
        'Rektör',
        'Rektör yardımcısı',
        'Remayözcü',
        'Ressam',
        'Resepsiyon memuru',
        'Rot balansçı',
        'Radyoloji teknisyeni/teknikeri',
        'Saat tamircisi',
        'Saatçi',
        'Sağlık teknisyeni',
        'Sahil koruma',
        'Saksofoncu',
        'Salepçi',
        'Sanat yönetmeni',
        'Sanayici',
        'Sansürcü',
        'Santral memuru',
        'Saraç',
        'Sarraf',
        'Satış elemanı',
        'Savcı',
        'Saz şairi',
        'Sekreter',
        'Sepetçi',
        'Serbest muhasebeci mali müşavir',
        'Ses teknisyeni',
        'Seyis',
        'Sınırlı baş makinist',
        'Sicil memuru',
        'Sigortacı',
        'Sihirbaz',
        'Silahçı',
        'Silindir operatörü',
        'Simitçi',
        'Simyacı',
        'Sistem mühendisi',
        'Sistem yöneticisi',
        'Soğuk demirci',
        'Sokak çalgıcısı',
        'Sokak satıcısı',
        'Son ütücü',
        'Sorgu hâkimi',
        'Sosyal hizmet uzmanı',
        'Sosyolog',
        'Spiker',
        'Stenograf',
        'Stilist',
        'Striptizci',
        'Su tesisatçısı',
        'Subay',
        'Sucu',
        'Suflör',
        'Sulh hâkimi',
        'Sunucu',
        'Susuz araç yıkama',
        'Sünnetçi',
        'Sürveyan',
        'Sütanne',
        'Sütçü',
        'Şahinci',
        'Şair',
        'Şapel papazı',
        'Şapkacı',
        'Şarap üreticisi',
        'Şarkıcı',
        'Şarkı sözü yazarı',
        'Şarküter',
        'Şekerci',
        'Şemsiyeci',
        'Şifre çözümleyici',
        'Şimşirci',
        'Şoför',
        'Şarapçı',
        'Şarküteri, Gıda Pazarları ve Bakkal Satış Elemanı',
        'Şehir Plancısı',
        'Tabakçı',
        'Tabelacı',
        'Tahsildar',
        'Taksici',
        'Tarım işçisi',
        'Tarihçi',
        'Tasarımcı',
        'Taşçı',
        'Taşlayıcı',
        'Tatlıcı',
        'Tavukçu',
        'Tayfa',
        'Tefeci',
        'Teğmen',
        'Tekniker',
        'Teknisyen',
        'Teknoloji uzmani',
        'Telefon operatörü',
        'Telekız',
        'Televizyon tamircisi',
        'Tellal',
        'Temizlikçi',
        'Temsilci',
        'Terapist',
        'Tercüman',
        'Terzi',
        'Tesgahtar',
        'Tesisatçı',
        'Tesviyeci',
        'Test mühendisi',
        'Test pilotu',
        'Teşrifatçı',
        'Tiyatro yönetmeni',
        'Tombalacı',
        'Topçu',
        'Tornacı',
        'Turizmci',
        'Tuğgeneral',
        'Tuhafiyeci',
        'Turşucu',
        'Tuzcu',
        'Tümamiral',
        'Tümgeneral',
        'Uçuş teknisyeni',
        'Ulaşım sorumlusu',
        'Ustabaşı',
        'Uydu antenci',
        'Uzay mühendisi',
        'Uzay bilimcisi',
        'Uzman Jandarma',
        'Uzman Çavuş',
        'Üretici',
        'Ürolog',
        'Ütücü',
        'Üzümcü',
        'Üst Düzey Yönetici',
        'Vaiz',
        'Vali',
        'Vergi denetmeni',
        'Vergi müfettişi',
        'Vergi tahakkuk memuru',
        'Veritabanı yöneticisi',
        'Veri hazırlama ve kontrol işletmeni',
        'Vestiyerci',
        'Veteriner hekim',
        'Veteriner sağlık teknikeri',
        'Veteriner sağlık teknisyeni',
        'Veznedar',
        'Video editörü',
        'Vinç operatörü',
        'Vitrinci',
        'Viyolonselci',
        'Vatman',
        'Yarbay',
        'Yardımcı hakem',
        'Yardımcı hizmetli',
        'Yardımcı pilot',
        'Yargıç',
        'Yatırım uzmanı',
        'Yayıncı',
        'Yazar',
        'Yazı işleri müdürü',
        'Yazılım mühendisi',
        'Yelkenci',
        'Yeminli mali müşavir',
        'Yeminli tercüman',
        'Yer gösterici',
        'Yer teknisyeni',
        'Yerölçmeci',
        'Yoğurtçu',
        'Yol bekçisi',
        'Yorgancı',
        'Yorumcu',
        'Yönetici',
        'Yüzücü',
        'Yönetmen',
        'Yıkıcı',
        'Zabıta',
        'Zoolog'
    )
    return jo