class Category: 
    "kategoriler eylence/ders/"
    def __init__(self):
        self.faculties = [
            # fakülteler
            'Mühendislik',
            "Tip",
            "Fen edebiyat",
            "İktisadi ve idari bilimleri",
            "Eğitim",
            "Diş hekimliği",
            "Mimarlik",
            "İslahiye iktisadi ve idari bilimleri",
            "Güzel sanatlar",
            "Sağlik bilimleri",
            "Hukuk",
            "İlahiyat",
            "İletişim",
            "Havacilik ve uzay mühendisliği",
            "Turizm"
        ]
        self.yüksekokul = [
            # yüksekokular
            "Türk musikisi devlet konservatuari",
            "Beden eğitimi ve spor",
            "Yabanci diller",
            "Sivil havacilik",
        ]
        self.meslek_yüksekokul = [
            # meslek yüksek okullar
            "Teknik bilimler",
            "Sosyal bilimler",
            "Sağlik hizmetleri",
            "Turizm ve Otelcilik",
            "Islahiye",
            "BÜRO HİZMETLERİ VE SEKRETERLİK BÖLÜMÜ",
            "BİLGİSAYAR TEKNOLOJİLERİ BÖLÜMÜ",
            "BİTKİSEL VE HAYVANSAL ÜRETİMİ BÖLÜMÜ",
            "FİNANS VE BANKACILIK BÖLÜMÜ",
            "GIDA İŞLEMLERİ BÖLÜMÜ",
            "DIŞ TİCARET BÖLÜMÜ",
            "YÖNETİM VE ORGANİZASYON BÖLÜMÜ",
            "PAZARLAMA VE REKLAMCILIK BÖLÜMÜ",
            "TERAPİ VE REHABİLİTASYON BÖLÜMÜ",
            "SAĞLIK BAKIM HİZMETLERİ BÖLÜMÜ",
            "DİŞÇİLİK HİZMETLERİ BÖLÜMÜ",
            "OTEL, LOKANTA VE İKRAM HİZMETLERİ BÖLÜMÜ",
            "SEYAHAT-TURİZM VE EĞLENCE HİZMETLERİ BÖLÜMÜ",
            "Adalet",
            "Lojistik",
            "İşletme Yönetimi",
            "İş Sağliği ve Güvenliği",
            "Bilgisayar Programciliği",
            "Özel Güvenlik ve Koruma",
            "Sivil Savunma ve İtfaiyecilik",
            "Sosyal Güvenlik",
            "MÜLKİYETİ KORUMA VE GÜVENLİK BÖLÜMÜ",
            "VETERİNERLİK BÖLÜMÜ",
            "MUHASEBE VE VERGİ BÖLÜMÜ",
            "Diş ticaret",
            "Yönetim ve organizasyon",
            "Bitkisel ve hayvansal üretim",
            "el sanatlari",
            "gida işleme",
            "malzeme ve malzeme işleme",
            "tekstil,giyim,ayakkabi,deri",
            "mülkiyet koruma ve güvenlik",
            "makine ve metal teknolojileri",
            "kimya ve kimyasal işleme teknolojileri",
            "TIBBİ HİZMETLER VE TEKNİKLER BÖLÜMÜ",
            "BİTKİSEL VE HAYVANSAL ÜRETİM BÖLÜMÜ",
            ]

class Subcategory:
    def muhendislik():
        en = [ # mühendislik dallari
            "Makine",
            "Elektrik ve elektronik",
            "Gida",
            "Fizik",
            "İnşaat",
            "Tekstil",
            "Endüstri",
            "Bigisayar",
            "Yazilim",
            "Metalurji ve malzeme",
            "Enerji sistemleri",
            "Biyoproses ve kimya",
            "Optik ve akustik",
        ]
        return en

    def tip():
        me = [ # tipin dallari
            "Dahili tip birimleri",
            "Cerrahi tip birimleri",
            "Temel tip birimleri",
        ]
        return me

    def fen_edebiyat():
        sl = [ # fen edebiyat
            "Tarih",
            "Matematik",
            "Türk dili ve edebiyat",
            "Biyoloji",
            "Bati dilleri ve edebiyat",
            "Kimya",
            "Arkeoloji",
            "Sosyoloji",
            "Kültür varliklarini koruma ve onarim",
            "İstatislik",
            "Psikoloji",
            "Çoğrafya",
            "Felsefe",
            "Doğu dilleri ve edebiyati",
        ]
        return sl
    
    def iktisadi_ve_idari_bilimleri():
        eaas = [ # iktisadi ve  idari
            "İktisat",
            "İşletme",
            "Uluslar arasi ticaret ve lojistik",
            "Kamu yönetim",
            "Maliye",
            "Küresel siyaset ve uluslararasi ilişkiler",
        ]
        return eaas

    def egitim():
        ed = [ # eğitim
            "Matematik ve fen bilimleri",
            "Güzel sanatlar",
            "Türkçe ve sosyal bilimler",
            "Yabanci diller",
            "Eğitim yönetimi anabilim dali",
            "Eğitim programlari ve öğretim adabilim dali",
            "Rehberlik ve psikojik danişma anabilim dali",
            "Eğitimin felsefesi,sosyal ve tarihi temelleri anabilim dali",
            "Hayat boyu öğrenme ve yetişkin eğitimi anabilim dali",
            "Öğretim teknolojileri anabilim dali",
            "Eğitimde ölçme ve değerlendirme anabilim dali",
            "Bilgisayar ve öğretim teknolojileri",
            "Okul öncesi eğitimi anabilim dali",
            "Sinif eğitimi anabilim dali",
            "Özel yetenekliler eğitimi anabilim dali",
            "Zihinsel engelliler eğitimi anabilim dali",
            "Görme engelliler eğitimi anabilim dali",
            "İşitme engelliler eğitimi anabilim dali",
            "eğitimi anabilim dali",
        ]
        return ed

    def dis_hekimligi():
        de = [ # diş 
            "Ağiz Diş ve Çene Cerrahisi AD.",
            "Endodonti AD.",
            "Oral Diagnoz ve Radyoloji AD.",
            "Ortodonti AD.",
            "Pedodonti AD.",
            "Periodontoloji AD.",
            "Protetik Diş Tedavisi AD.",
            "Restoratif Diş Tedavisi AD.",
        ]
        return de

    def mimarlik():
        arc = [ # mimar
            "ŞEHİR VE BÖLGE PLANLAMA BÖLÜMÜ",
            "ENDÜSTRİ ÜRÜNLERİ TASARIMI BÖLÜMÜ",
            "MİMARLIK BÖLÜMÜ",
            "İÇ MİMARLIK BÖLÜMÜ",
        ]
        return arc

    def islahiye_iktisadi_ve_idari_bilimleri():
        ieaas = [ # İslahiye İktisadi ve İdari Bilimler Fakültesi
            "EKONOMETRİ",
            "ULUSLARARASI İLİŞKİLER",
            "MALİYE",
            "KAMU YÖNETİMİ",
            "İKTİSAT",
            "İŞLETME",
        ]
        return ieaas

    def guzel_sanatlar():
        fi = [ # güzel sanatlar
            "GASTRONOMİ VE MUTFAK SANATLARI BÖLÜMÜ",
            "MODA VE TEKSTİL TASARIMI BÖLÜMÜ",
            "SAHNE VE GÖSTERİ SANATLARI BÖLÜMÜ",
            "GELENEKSEL TÜRK EL SANATLARI BÖLÜMÜ",
            "SİNEMA VE TELEVİZYON BÖLÜMÜ",
            "FOTOĞRAF BÖLÜMÜ",
            "SERAMİK VE CAM BÖLÜMÜ",
            "RESİM BÖLÜMÜ",
            "HEYKEL BÖLÜMÜ",
            "GRAFİK BÖLÜMÜ",
        ]
        return fi

    def saglik_bilimleri():
        he = [ #sağlik
            "FİZYOTERAPİ VE REHABİLİTASYON",
            "DİL VE KONUŞMA TERAPİSİ",
            "ODYOLOJİ",
            "BESLENME VE DİYETETİK",
            "SAĞLIK YÖNETİMİ",
            "SOLUNUM TERAPİSTLİĞİ",
            "EBELİK",
            "HEMŞİRELİK",
        ]
        return he

    def hukuk():
        la = [ # hukuk 
            "HUKUK FAKÜLTESİ", 
            "ANAYASA HUKUKU ANABİLİM DALI", 
            "CEZA VE CEZA MUHAKEMESİ HUKUKU ANABİLİM DALI", 
            "GENEL KAMU HUKUKU ANABİLİM DALI", 
            "HUKUK FELSEFESİ VE SOSYOLOJİSİ ANABİLİM DALI", 
            "HUKUK TARİHİ ANABİLİM DALI", 
            "MALİ HUKUK ANABİLİM DALI", 
            "MİLLETLERARASI HUKUK ANABİLİM DALI", 
            "İDARE HUKUKU ANABİLİM DALI", 
            "İNSAN HAKLARI ANABİLİM DALI", 
            "İSLAM HUKUKU ANABİLİM DALI", 
            "TİCARET HUKUKU ANABİLİM DALI", 
            "AVRUPA BİRLİĞİ HUKUKU ANABİLİM DALI", 
            "DENİZ HUKUKU ANABİLİM DALI", 
            "KARŞILAŞTIRMALI HUKUK ANABİLİM DALI", 
            "MEDENİ HUKUK ANABİLİM DALI", 
            "MEDENİ USUL VE İCRA İFLAS HUKUKU ANABİLİM DALI",
            "MİLLETLERARASI ÖZEL HUKUK ANABİLİM DALI", 
            "ROMA HUKUKU ANABİLİM DALI", 
            "İŞ VE SOSYAL GÜVENLİK HUKUKU ANABİLİM DALI",
        ]
        return la

    def ilahiyat():
        th = [ # ilahiyat
            "Tefsir",
            "Hadis",
            "Kelam",
            "İslam Hukuku",
            "İslam Mezhepleri Tarihi",
            "Tasavvuf",
            "Arap Dili ve Belagati",
            "Kurani Kerim Okuma ve Kiraat İlmi",
            "Din Eğitimi",
            "Dinler Tarihi",
            "İslam Felsefesi",
            "Din Sosyolojisi",
            "Din Psikolojisi",
            "Felsefe Tarihi",
            "Mantik",
            "İslam Tarihi",
            "Türk İslam Edebiyati",
            "Türk İslam Sanatlari Tarihi",
            "Türk Din Musikisi",
        ]
        return th

    def iletisim():
        co = [ # iletişim
            "Gazetecilik",
            "Halkla ilişkiler ve tanitim",
            "Radyo, tv ve sinema",
            "İletişim enformatiği",
            "Reklamcilik",
        ]
        return co

    def havaclk_ve_uzay_mühendisligi():
        ae = [ # HAVACILIK VE UZAY BİLİMLERİ FAKÜLTESİ
            "HAVACILIK YÖNETİMİ BÖLÜMÜ",
            "UÇAK VE UZAY MÜHENDİSLİĞİ BÖLÜMÜ",
            "PİLOTAJ BÖLÜMÜ",
        ]
        return ae
    def all():
        all_ = [
            "Makine",
            "Elektrik ve elektronik",
            "Gida",
            "Fizik",
            "İnşaat",
            "Tekstil",
            "Endüstri",
            "Bigisayar",
            "Yazilim",
            "Metalurji ve malzeme",
            "Enerji sistemleri",
            "Biyoproses ve kimya",
            "Optik ve akustik",
            "Dahili tip birimleri",
            "Cerrahi tip birimleri",
            "Temel tip birimleri",
            "Tarih",
            "Matematik",
            "Türk dili ve edebiyat",
            "Biyoloji",
            "Bati dilleri ve edebiyat",
            "Kimya",
            "Arkeoloji",
            "Sosyoloji",
            "Kültür varliklarini koruma ve onarim",
            "İstatislik",
            "Psikoloji",
            "Çoğrafya",
            "Felsefe",
            "Doğu dilleri ve edebiyati",
            "İktisat",
            "İşletme",
            "Uluslar arasi ticaret ve lojistik",
            "Kamu yönetim",
            "Maliye",
            "Küresel siyaset ve uluslararasi ilişkiler",
            "Matematik ve fen bilimleri",
            "Güzel sanatlar",
            "Türkçe ve sosyal bilimler",
            "Yabanci diller",
            "Eğitim yönetimi anabilim dali",
            "Eğitim programlari ve öğretim adabilim dali",
            "Rehberlik ve psikojik danişma anabilim dali",
            "Eğitimin felsefesi,sosyal ve tarihi temelleri anabilim dali",
            "Hayat boyu öğrenme ve yetişkin eğitimi anabilim dali",
            "Öğretim teknolojileri anabilim dali",
            "Eğitimde ölçme ve değerlendirme anabilim dali",
            "Bilgisayar ve öğretim teknolojileri",
            "Okul öncesi eğitimi anabilim dali",
            "Sinif eğitimi anabilim dali",
            "Özel yetenekliler eğitimi anabilim dali",
            "Zihinsel engelliler eğitimi anabilim dali",
            "Görme engelliler eğitimi anabilim dali",
            "İşitme engelliler eğitimi anabilim dali",
            "eğitimi anabilim dali",
            "Ağiz Diş ve Çene Cerrahisi AD.",
            "Endodonti AD.",
            "Oral Diagnoz ve Radyoloji AD.",
            "Ortodonti AD.",
            "Pedodonti AD.",
            "Periodontoloji AD.",
            "Protetik Diş Tedavisi AD.",
            "Restoratif Diş Tedavisi AD.",
            "ŞEHİR VE BÖLGE PLANLAMA BÖLÜMÜ",
            "ENDÜSTRİ ÜRÜNLERİ TASARIMI BÖLÜMÜ",
            "MİMARLIK BÖLÜMÜ",
            "İÇ MİMARLIK BÖLÜMÜ",
            "EKONOMETRİ",
            "ULUSLARARASI İLİŞKİLER",
            "MALİYE",
            "KAMU YÖNETİMİ",
            "İKTİSAT",
            "İŞLETME",
            "GASTRONOMİ VE MUTFAK SANATLARI BÖLÜMÜ",
            "MODA VE TEKSTİL TASARIMI BÖLÜMÜ",
            "SAHNE VE GÖSTERİ SANATLARI BÖLÜMÜ",
            "GELENEKSEL TÜRK EL SANATLARI BÖLÜMÜ",
            "SİNEMA VE TELEVİZYON BÖLÜMÜ",
            "FOTOĞRAF BÖLÜMÜ",
            "SERAMİK VE CAM BÖLÜMÜ",
            "RESİM BÖLÜMÜ",
            "HEYKEL BÖLÜMÜ",
            "GRAFİK BÖLÜMÜ",
            "FİZYOTERAPİ VE REHABİLİTASYON",
            "DİL VE KONUŞMA TERAPİSİ",
            "ODYOLOJİ",
            "BESLENME VE DİYETETİK",
            "SAĞLIK YÖNETİMİ",
            "SOLUNUM TERAPİSTLİĞİ",
            "EBELİK",
            "HEMŞİRELİK",
            "HUKUK FAKÜLTESİ", 
            "ANAYASA HUKUKU ANABİLİM DALI", 
            "CEZA VE CEZA MUHAKEMESİ HUKUKU ANABİLİM DALI", 
            "GENEL KAMU HUKUKU ANABİLİM DALI", 
            "HUKUK FELSEFESİ VE SOSYOLOJİSİ ANABİLİM DALI", 
            "HUKUK TARİHİ ANABİLİM DALI", 
            "MALİ HUKUK ANABİLİM DALI", 
            "MİLLETLERARASI HUKUK ANABİLİM DALI", 
            "İDARE HUKUKU ANABİLİM DALI", 
            "İNSAN HAKLARI ANABİLİM DALI", 
            "İSLAM HUKUKU ANABİLİM DALI", 
            "TİCARET HUKUKU ANABİLİM DALI", 
            "AVRUPA BİRLİĞİ HUKUKU ANABİLİM DALI", 
            "DENİZ HUKUKU ANABİLİM DALI", 
            "KARŞILAŞTIRMALI HUKUK ANABİLİM DALI", 
            "MEDENİ HUKUK ANABİLİM DALI", 
            "MEDENİ USUL VE İCRA İFLAS HUKUKU ANABİLİM DALI",
            "MİLLETLERARASI ÖZEL HUKUK ANABİLİM DALI", 
            "ROMA HUKUKU ANABİLİM DALI", 
            "İŞ VE SOSYAL GÜVENLİK HUKUKU ANABİLİM DALI",
            "Tefsir",
            "Hadis",
            "Kelam",
            "İslam Hukuku",
            "İslam Mezhepleri Tarihi",
            "Tasavvuf",
            "Arap Dili ve Belagati",
            "Kurani Kerim Okuma ve Kiraat İlmi",
            "Din Eğitimi",
            "Dinler Tarihi",
            "İslam Felsefesi",
            "Din Sosyolojisi",
            "Din Psikolojisi",
            "Felsefe Tarihi",
            "Mantik",
            "İslam Tarihi",
            "Türk İslam Edebiyati",
            "Türk İslam Sanatlari Tarihi",
            "Türk Din Musikisi",
            "Gazetecilik",
            "Halkla ilişkiler ve tanitim",
            "Radyo, tv ve sinema",
            "İletişim enformatiği",
            "Reklamcilik",
            "HAVACILIK YÖNETİMİ BÖLÜMÜ",
            "UÇAK VE UZAY MÜHENDİSLİĞİ BÖLÜMÜ",
            "PİLOTAJ BÖLÜMÜ",
        ]
        return all_


def university():
    uni = (
        'Abant İzzet Baysal Üniversitesi',
        'Abdullah Gül Üniversitesi',
        'Adana Bilim ve Teknoloji Üniversitesi',
        'Adiyaman Üniversitesi',
        'Adnan Menderes Üniversitesi',
        'Afyon Kocatepe Üniversitesi',
        'Ağri İbrahim Çeçen Üniversitesi',
        'Ahi Evran Üniversitesi',
        'Akdeniz Üniversitesi',
        'Aksaray Üniversitesi',
        'Alanya Alaaddin Keykubat Üniversitesi',
        'Amasya Üniversitesi',
        'Anadolu Üniversitesi',
        'Ankara Üniversitesi',
        'Ankara Sosyal Bilimler Üniversitesi',
        'Ardahan Üniversitesi',
        'Artvin Çoruh Üniversitesi',
        'Atatürk Üniversitesi',
        'Balikesir Üniversitesi',
        'Bandirma Onyedi Eylül Üniversitesi',
        'Bartin Üniversitesi',
        'Batman Üniversitesi',
        'Bayburt Üniversitesi',
        'Bilecik Şeyh Edebali Üniversitesi',
        'Bingöl Üniversitesi',
        'Bitlis Eren Üniversitesi',
        'Boğaziçi Üniversitesi',
        'Bozok Üniversitesi',
        'Bursa Teknik Üniversitesi',
        'Devlet Üniversitesi',
        'Celal Bayar Üniversitesi',
        'Cumhuriyet Üniversitesi',
        'Çanakkale Onsekiz Mart Üniversitesi',
        'Çankiri Karatekin Üniversitesi',
        'Çukurova Üniversitesi',
        'Dicle Üniversitesi',
        'Dokuz Eylül Üniversitesi',
        'Dumlupinar Üniversitesi',
        'Düzce Üniversitesi',
        'Ege Üniversitesi',
        'Erciyes Üniversitesi',
        'Erzincan Üniversitesi',
        'Erzurum Teknik Üniversitesi',
        'Eskişehir Osmangazi Üniversitesi',
        'Firat Üniversitesi',
        'Galatasaray Üniversitesi',
        'Gazi Üniversitesi',
        'Gaziantep Üniversitesi',
        'Gaziosmanpaşa Üniversitesi',
        'Gebze Teknik Üniversitesi',
        'Giresun Üniversitesi',
        'Gümüşhane Üniversitesi',
        'Hacettepe Üniversitesi',
        'Hakkari Üniversitesi',
        'Harran Üniversitesi',
        'Hitit Üniversitesi',
        'Iğdir Üniversitesi',
        'İnönü Üniversitesi',
        'İskenderun Teknik Üniversitesi',
        'İstanbul Medeniyet Üniversitesi',
        'İstanbul Üniversitesi',
        'İstanbul Teknik Üniversitesi',
        'İzmir Kâtip Çelebi Üniversitesi',
        'Kafkas Üniversitesi',
        'Kahramanmaraş Sütçü İmam Üniversitesi',
        'Karabük Üniversitesi',
        'Karadeniz Teknik Üniversitesi',
        'Karamanoğlu Mehmetbey Üniversitesi',
        'Kastamonu Üniversitesi',
        'Kirikkale Üniversitesi',
        'Kirklareli Üniversitesi',
        'Kilis 7 Aralik Üniversitesi',
        'Kocaeli Üniversitesi',
        'Necmettin Erbakan Üniversitesi',
        'Devlet Üniversitesi',
        'Mardin Artuklu Üniversitesi',
        'Marmara Üniversitesi',
        'Mehmet Akif Ersoy Üniversitesi',
        'Mersin Üniversitesi',
        'Mimar Sinan Güzel Sanatlar Üniversitesi',
        'Muğla Sitki Koçman Üniversitesi',
        'Mustafa Kemal Üniversitesi',
        'Muş Alparslan Üniversitesi',
        'Namik Kemal Üniversitesi',
        'Nevşehir Haci Bektaş Veli Üniversitesi',
        'Niğde Üniversitesi',
        'Ondokuz Mayis Üniversitesi',
        'Ordu Üniversitesi',
        'Orta Doğu Teknik Üniversitesi',
        'Osmaniye Korkut Ata Üniversitesi',
        'Pamukkale Üniversitesi',
        'Recep Tayyip Erdoğan Üniversitesi',
        'Sakarya Üniversitesi',
        'Selçuk Üniversitesi',
        'Siirt Üniversitesi',
        'Sinop Üniversitesi',
        'Süleyman Demirel Üniversitesi',
        'Şirnak Üniversitesi',
        'Trakya Üniversitesi',
        'Tunceli Üniversitesi',
        'Türk Alman Üniversitesi',
        'Türkiye Sağlik Bilimleri Üniversitesi',
        'Türkiye Uluslararasi İslam, Bilim ve Teknoloji Üniversitesi',
        'Uludağ Üniversitesi',
        'Uşak Üniversitesi',
        'Yalova Üniversitesi',
        'Yildiz Teknik Üniversitesi',
        'Yildirim Beyazit Üniversitesi',
        'Yüzüncü Yil Üniversitesi',
        'Bülent Ecevit Üniversitesi',
        'Acibadem Üniversitesi',
        'Akev Üniversitesi',
        'Alanya Hamdullah Emin Paşa Üniversitesi',
        'Atilim Üniversitesi',
        'Avrasya Üniversitesi',
        'Bahçeşehir Üniversitesi',
        'Başkent Üniversitesi',
        'Beykent Üniversitesi',
        'Bezmiâlem Vakif Üniversitesi',
        'Bilkent Üniversitesi',
        'Biruni Üniversitesi',
        'Bursa Orhangazi Üniversitesi',
        'Canik Başari Üniversitesi',
        'Çankaya Üniversitesi',
        'Çağ Üniversitesi',
        'Doğuş Üniversitesi',
        'Fatih Sultan Mehmet Üniversitesi',
        'Fatih Üniversitesi',
        'Gedik Üniversitesi',
        'Gediz Üniversitesi',
        'Haliç Üniversitesi',
        'Hasan Kalyoncu Üniversitesi',
        'Işik Üniversitesi',
        'İbn-u Haldun Üniversitesi',
        'İpek Üniversitesi',
        'İstanbul 29 Mayis Üniversitesi',
        'İstanbul Arel Üniversitesi',
        'İstanbul Aydin Üniversitesi',
        'İstanbul Bilgi Üniversitesi',
        'İstanbul Bilim Üniversitesi',
        'İstanbul Esenyurt Üniversitesi',
        'İstanbul Gelişim Üniversitesi',
        'İstanbul Kemerburgaz Üniversitesi',
        'İstanbul Kültür Üniversitesi',
        'İstanbul Medipol Üniversitesi',
        'İstanbul Rumeli Üniversitesi',
        'İstanbul Sabahattin Zaim Üniversitesi',
        'İstanbul Şehir Üniversitesi',
        'İstanbul Ticaret Üniversitesi',
        'İstinye Üniversitesi',
        'İzmir Ekonomi Üniversitesi',
        'İzmir Üniversitesi',
        'Kadir Has Üniversitesi',
        'Karatay Üniversitesi',
        'Koç Üniversitesi',
        'Konya Gida Tarim Üniversitesi',
        'Maltepe Üniversitesi',
        'MEF Üniversitesi',
        'Melikşah Üniversitesi',
        'Mevlana Üniversitesi',
        'Murat Hüdavendigar Üniversitesi',
        'Nişantaşi Üniversitesi',
        'Nuh Naci Yazgan Üniversitesi',
        'Okan Üniversitesi',
        'Özyeğin Üniversitesi',
        'Piri Reis Üniversitesi',
        'Sabanci Üniversitesi',
        'Sanko Üniversitesi',
        'Selahattin Eyyubi Üniversitesi',
        'Süleyman Şah Üniversitesi',
        'Şifa Üniversitesi',
        'TED Üniversitesi',
        'TOBB Ekonomi ve Teknoloji Üniversitesi',
        'Toros Üniversitesi',
        'Turgut Özal Üniversitesi',
        'Türk Hava Kurumu Üniversitesi',
        'Ufuk Üniversitesi',
        'Uluslararasi Antalya Üniversitesi',
        'Üsküdar Üniversitesi',
        'Yaşar Üniversitesi',
        'Yeditepe Üniversitesi',
        'Yeni Yüzyil Üniversitesi',
        'Yüksek İhtisas Üniversitesi',
        'Zirve Üniversitesi',
        'Kanuni Üniversitesi',
    )
    return uni
def jop():
    jo = (
        "Öğrenci",
        'Acentaci',
        'Acil durum yönetmeni',
        'Adli tabip',
        'Agronomist',
        'Ağ yöneticisi',
        'Aşçi',
        'Aşçibaşi',
        'Ahşap tekne yapimcisi',
        'Aile hekimi',
        'Aktar',
        'Akortçu',
        'Aktör',
        'Aktüer',
        'Aktris',
        'Akustikçi',
        'Albay',
        'Ambalajci',
        'Ambarci',
        'Ambulans şoförü',
        'Amiral',
        'Anahtarci',
        'Analist',
        'Anestezi uzmani',
        'Anestezi Teknikeri',
        'Animatör',
        'Antika saticisi',
        'Antropolog',
        'Apartman yöneticisi',
        'Araba saticisi',
        'Araba yikayicisi',
        'Arabaci',
        'Arabulucu',
        'Araştirmaci',
        'Arici',
        'Arkeolog',
        'Armatör',
        'Arpist',
        'Arşivci',
        'Artist',
        'Asansörcü',
        'Asistan',
        'Asker',
        'Astrofizikçi',
        'Astrolog',
        'Astronom',
        'Astronot',
        'Astsubay',
        'Atlet',
        'Av bekçisi',
        'Avci',
        'Avizeci',
        'Avukat',
        'Ayakçi (otogar, lokanta)',
        'Ayakkabi boyacisi',
        'Ayakkabi tamircisi',
        'Ayakkabici',
        'Ayi oynaticisi',
        'Araba tamircisi',
        'Bacaci',
        'Badanaci',
        'Baharatçi',
        'Bahçe bitkileri uzmani',
        'Bahçivan',
        'Bakan',
        'Bakici',
        'Bakirci',
        'Bakkal',
        'Bakteriyolog',
        'Balikçi',
        'Balon pilotu',
        'Bankaci',
        'Banker',
        'Barmen',
        'Barmeyd',
        'Basketbolcu',
        'Başbakan',
        'Başçavuş',
        'Başdümenci',
        'Başhemşire',
        'Başkan',
        'Başkomiser',
        'Başpiskopos',
        'Başrahip',
        'Belediye başkani',
        'Belediye meclisi üyesi',
        'Benzinci',
        'Berber',
        'Besteci',
        'Biletçi',
        'Bilgisayar mühendisi',
        'Bilgisayar programcisi',
        'Bilgisayar tamircisi',
        'Bilimadami',
        'Bilirkişi',
        'Binicilik',
        'Biraci',
        'Bisikletçi',
        'Biyografi yazari',
        'Biyolog',
        'Bobinajci',
        'Bombaci',
        'Bomba imhaci',
        'Borsaci',
        'Borucu',
        'Botanikçi',
        'Boyaci',
        'Bozaci',
        'Böcekbilimci',
        'Börekçi',
        'Bulaşikçi',
        'Buldozer operatörü',
        'Bütçe uzmani',
        'Büyükelçi',
        'Besicilik',
        'Bebek Bakicisi',
        'Bilgi İşlemci',
        'Camci',
        'Cerrah',
        'Celep',
        'Cellat',
        'Cost Control',
        'Cillopçu',
        'Cumhurbaşkani',
        'Çamaşirci',
        'Çantaci',
        'Çarkçi',
        'Çatici',
        'Çayci',
        'Çevirmen',
        'Çevrebilimci',
        'Çevre Mühendisi',
        'Çeyizci',
        'Çikikçi',
        'Çikrikçi',
        'Çiçekçi',
        'Çiftçi',
        'Çiftlik işletici',
        'Çikolataci',
        'Çilingir',
        'Çinici',
        'Çitçi',
        'Çoban',
        'Çocuk doktoru',
        'Çorapçi',
        'Çöp işçisi',
        'Çöpçü',
        'Çirak',
        'Çevik Kuvvet',
        'Dadi',
        'Daktilograf',
        'Dalgiç',
        'Damitici',
        'Danişman',
        'Dansöz',
        'Davulcu',
        'Debbağ',
        'Dedektif',
        'Değirmen işçisi',
        'Değirmenci',
        'Demirci',
        'Demiryolu işçisi',
        'Denetçi',
        'Denetleyici',
        'Denizci',
        'Depocu',
        'Derici',
        'Desinatör',
        'Devlet memuru',
        'Dilci',
        'Dilenci',
        'Diplomat',
        'Diş hekimi',
        'Diyetisyen',
        'Dizgici',
        'Doğalgazci',
        'Doğramaci',
        'Doğum uzmani',
        'Dok işçisi',
        'Dokumaci',
        'Doktor',
        'Dondurmaci',
        'Dökümcü',
        'Döşemeci',
        'Dövizci',
        'Dublajci',
        'Duvarci',
        'Dümenci',
        'diş teknisyeni',
        'Ebe(kadin doğum)',
        'Eczaci',
        'Eczaci kalfasi',
        'Editör',
        'Eğitimci',
        'Eğitmen',
        'Ekonomist',
        'Elektrik mühendisi',
        'Elektronik mühendisi',
        'Elektrikçi',
        'Eleştirmen',
        'Embriyolog',
        'Emlakçi',
        'Emniyet amiri',
        'Emniyet genel müdürü',
        'Endüstri mühendisi',
        'Endüstri sistemleri mühendisi',
        'Enstrüman imalatçisi',
        'Ergonomist',
        'Eskici',
        'Estetisyen',
        'Etolojist',
        'Etimolog',
        'Etnolog',
        'Ev hanimi',
        'Fabrika işçisi',
        'Fahişe',
        'Falci',
        'Fermantasyon işçisi',
        'Fiçici',
        'Firinci',
        'Figüran',
        'Film yapimcisi',
        'Film yönetmeni',
        'Filozof',
        'Finansör',
        'Fizikçi',
        'Fizyonomist',
        'Fizyoterapist',
        'Acil tip teknisyeni',
        'Fon yöneticisi',
        'Forklift operatörü',
        'Fotoğrafçi',
        'Futbolcu',
        'Gardiyan',
        'Galerici',
        'Garson',
        'Gazete dağiticisi',
        'Gazete saticisi',
        'Gazeteci',
        'Gelir uzmani',
        'Gelir uzman yardimcisi',
        'Gemici',
        'General',
        'Genetik mühendisi',
        'Geyşa',
        'Gezgin',
        'Gezici vaiz',
        'Gida mühendisi',
        'Gitarist',
        'Gondolcu',
        'Gökbilimci',
        'Göz doktoru',
        'Gözetmen',
        'Gözlükçü',
        'Grafiker',
        'Gramer uzmani',
        'Greyder operatörü',
        'Guru',
        'Güfteci',
        'Gümrük memuru',
        'Gümrük müşaviri',
        'Gümrük müşavir yardimcisi',
        'Gümrük uzmani',
        'Gündelikçi',
        'Güzellik uzmani',
        'Haberci',
        'Haddeci',
        'Haham',
        'Hakem',
        'Halici',
        'Halkbilimci',
        'Hamal',
        'Hamamci',
        'Hamurkâr',
        'Hareket memuru',
        'Haritaci',
        'Harita mühendisi',
        'Hastabakici',
        'Hattat',
        'Hava trafikçisi',
        'Havaci',
        'Haydut',
        'Hayvan bakicisi',
        'Hayvan terbiyecisi',
        'Hemşire',
        'Hesap uzmani',
        'Heykeltiraş',
        'Hirdavatçi',
        'Hirsiz',
        'Hidrolikçi',
        'Hizmetçi',
        'Hokkabaz',
        'Host',
        'Hostes',
        'Hukukçu',
        'Hurdaci',
        'Irgat',
        'Işikçi',
        'İcra memuru',
        'İç mimar',
        'İğneci',
        'İhracatçi',
        'İktisatçi',
        'İlahiyatçi',
        'İllüzyonist',
        'İmam',
        'İnsan kaynaklari uzmani',
        'İnşaat mühendisi',
        'İnşaatçi',
        'İpçi',
        'İplikçi',
        'İstatistikçi',
        'İstihkâmci',
        'İşaretçi',
        'İşçi',
        'İşletmeci',
        'İşletme mühendisi',
        'İşportaci',
        'İş ve uğraşi terapisti',
        'İtfaiyeci',
        'İthalatçi',
        'Jeofizik mühendisi',
        'Jeoloji mühendisi',
        'Jeolog',
        'Jeomorfolog',
        'Jinekolog',
        'Jimnastikçi',
        'Jokey',
        'Kabin görevlisi',
        'Kabuk soyucusu',
        'Kadin berberi',
        'Kadin terzisi',
        'Kâğitçi',
        'Kahveci',
        'Kâhya',
        'Kalayci',
        'Kalipçi',
        'Kaloriferci',
        'Kamarot',
        'Kameraman',
        'Kamyoncu',
        'Kapi saticisi',
        'Kapici',
        'Kaplamaci',
        'Kaportaci',
        'Kaptan',
        'Kardinal',
        'Kardiyolog',
        'Karikatürist',
        'Karoserci',
        'Karpuzcu',
        'Kasap',
        'Kasiyer',
        'Kat görevlisi',
        'Kâtip',
        'Kayikçi',
        'Kaymakam',
        'Kaynakçi',
        'Kazici',
        'Kebapçi',
        'Kemanci',
        'Kesimci',
        'Kirtasiyeci',
        'Kimyager',
        'Kimya mühendisi',
        'Kitapçi',
        'Klarnetçi',
        'Koleksiyoncu',
        'Komedyen',
        'Komisyoncu',
        'Komiser',
        'Konserveci',
        'Konsolos',
        'Konsomatris',
        'Kontrolör',
        'Konveyör operatörü',
        'Kopyalayici',
        'Koreograf',
        'Korgeneral',
        'Koramiral',
        'Korsan',
        'Koruma görevlisi',
        'Komiser',
        'Komiser yardimcisi',
        'Kozmolog',
        'Köfteci',
        'Kömürcü',
        'Köpek eğiticisi',
        'Köşe yazari',
        'Kuaför',
        'Kuşçu',
        'Kumarbaz',
        'Kumaşçi',
        'Kumcu',
        'Kuru temizlemeci',
        'Kuruyemişçi',
        'Kurye',
        'Kuşbilimci',
        'Kuyumcu',
        'Kürkçü',
        'Kütüphaneci',
        'Laborant',
        'Laboratuar işçisi',
        'Lahmacuncu',
        'Lehimci',
        'Levazimci',
        'Lobici',
        'Lokantaci',
        'Lokomotifçi',
        'Lostromo',
        'Lostraci',
        'Lokman',
        'Madenci',
        'Makasçi',
        'Makastar',
        'Maketçi',
        'Makinist',
        'Makine mühendisi',
        'Makine zabiti',
        'Makyajci',
        'Mali hizmetler uzmani',
        'Manastir baş rahibesi',
        'Manav',
        'Manifaturaci',
        'Manikürcü',
        'Manken',
        'Marangoz',
        'Masör',
        'Masöz',
        'Matador',
        'Matbaaci',
        'Matematikçi',
        'Matkapçi',
        'Memur',
        'Menajer',
        'Mermerci',
        'Metalurji mühendisi',
        'Meteoroloji uzmani',
        'Metin yazari',
        'Mevsimlik işçi',
        'Meydanci',
        'Meyhaneci',
        'Mezarci',
        'Midyeci',
        'Mikrobiyolog',
        'Milletvekili',
        'Mimar',
        'Misyoner',
        'Mobilyaci',
        'Modaci',
        'Model',
        'Modelci',
        'Modelist',
        'Montajci',
        'Montör',
        'Motor tamircisi',
        'Motorcu',
        'Muallim',
        'Muhabbet tellali',
        'Muhabir',
        'Muhafiz',
        'Muhasebeci',
        'Muhtar',
        'Mumyalayici',
        'Muzcu',
        'Mübaşir',
        'Müdür',
        'Müezzin',
        'Müfettiş',
        'Müşavir',
        'Mühendis',
        'Müneccim',
        'Mürebbiye',
        'Müsteşar',
        'Müteahhit',
        'Mütercim',
        'Müze müdürü',
        'Müzik yönetmeni',
        'Müzisyen',
        'Nalinci',
        'Nakişçi',
        'Nakliyeci',
        'Nalbant',
        'Nalbur',
        'Noter',
        'Obuaci',
        'Ocakçi',
        'Odaci',
        'Oduncu',
        'Okçu',
        'Okul müdürü',
        'Okutman',
        'Operatör',
        'Opera sanatçisi',
        'Orgcu',
        'Orgeneral',
        'Orman mühendisi',
        'Ornitolog (veya kuşbilimci)',
        'Otelci',
        'Oto elektrikçisi',
        'Oto tamircisi',
        'Oto yedek parçaci',
        'Overlokçu',
        'Oymaci',
        'Oyuncu',
        'Oyun hostesi',
        'Oyun yazari',
        'Oyuncakçi',
        'Oto lastik tamircisi',
        'Öğretmen',
        'Öğretim elemani',
        'Öğretim görevlisi',
        'Öğretim üyesi',
        'Örmeci',
        'Ön muhasebeci',
        'Ön muhasebe sorumlusu',
        'Ön muhasebe yardimci elemani',
        'Ön büro elemani',
        'Özel şoför',
        'Paketleyici',
        'Palyaço',
        'Pandomimci',
        'Pansiyoncu',
        'Pansumanci',
        'Papa',
        'Papaz',
        'Parali asker',
        'Park bekçisi',
        'Pastörizör',
        'Patolog',
        'Peçeteci',
        'Pencereci',
        'Perukçu',
        'Peyzaj mimari',
        'Peyzaj teknikeri',
        'Pideci',
        'Pilavci',
        'Pilot',
        'Piskopos',
        'Piyade',
        'Piyango saticisi',
        'Piyanist',
        'Polis memuru',
        'Polis şefi',
        'Polisajci',
        'Politikaci',
        'Pompaci',
        'Postaci',
        'Profesör',
        'Proktolog',
        'Protokol görevlisi',
        'Psikiyatr',
        'Psikolog',
        'Psikolojik danişmanlik ve rehberlik',
        'Paramedik',
        'Radyolog',
        'Redaktör',
        'Rehber',
        'Rejisör',
        'Reklamci',
        'Rektör',
        'Rektör yardimcisi',
        'Remayözcü',
        'Ressam',
        'Resepsiyon memuru',
        'Rot balansçi',
        'Radyoloji teknisyeni/teknikeri',
        'Saat tamircisi',
        'Saatçi',
        'Sağlik teknisyeni',
        'Sahil koruma',
        'Saksofoncu',
        'Salepçi',
        'Sanat yönetmeni',
        'Sanayici',
        'Sansürcü',
        'Santral memuru',
        'Saraç',
        'Sarraf',
        'Satiş elemani',
        'Savci',
        'Saz şairi',
        'Sekreter',
        'Sepetçi',
        'Serbest muhasebeci mali müşavir',
        'Ses teknisyeni',
        'Seyis',
        'Sinirli baş makinist',
        'Sicil memuru',
        'Sigortaci',
        'Sihirbaz',
        'Silahçi',
        'Silindir operatörü',
        'Simitçi',
        'Simyaci',
        'Sistem mühendisi',
        'Sistem yöneticisi',
        'Soğuk demirci',
        'Sokak çalgicisi',
        'Sokak saticisi',
        'Son ütücü',
        'Sorgu hâkimi',
        'Sosyal hizmet uzmani',
        'Sosyolog',
        'Spiker',
        'Stenograf',
        'Stilist',
        'Striptizci',
        'Su tesisatçisi',
        'Subay',
        'Sucu',
        'Suflör',
        'Sulh hâkimi',
        'Sunucu',
        'Susuz araç yikama',
        'Sünnetçi',
        'Sürveyan',
        'Sütanne',
        'Sütçü',
        'Şahinci',
        'Şair',
        'Şapel papazi',
        'Şapkaci',
        'Şarap üreticisi',
        'Şarkici',
        'Şarki sözü yazari',
        'Şarküter',
        'Şekerci',
        'Şemsiyeci',
        'Şifre çözümleyici',
        'Şimşirci',
        'Şoför',
        'Şarapçi',
        'Şarküteri, Gida Pazarlari ve Bakkal Satiş Elemani',
        'Şehir Plancisi',
        'Tabakçi',
        'Tabelaci',
        'Tahsildar',
        'Taksici',
        'Tarim işçisi',
        'Tarihçi',
        'Tasarimci',
        'Taşçi',
        'Taşlayici',
        'Tatlici',
        'Tavukçu',
        'Tayfa',
        'Tefeci',
        'Teğmen',
        'Tekniker',
        'Teknisyen',
        'Teknoloji uzmani',
        'Telefon operatörü',
        'Telekiz',
        'Televizyon tamircisi',
        'Tellal',
        'Temizlikçi',
        'Temsilci',
        'Terapist',
        'Tercüman',
        'Terzi',
        'Tesgahtar',
        'Tesisatçi',
        'Tesviyeci',
        'Test mühendisi',
        'Test pilotu',
        'Teşrifatçi',
        'Tiyatro yönetmeni',
        'Tombalaci',
        'Topçu',
        'Tornaci',
        'Turizmci',
        'Tuğgeneral',
        'Tuhafiyeci',
        'Turşucu',
        'Tuzcu',
        'Tümamiral',
        'Tümgeneral',
        'Uçuş teknisyeni',
        'Ulaşim sorumlusu',
        'Ustabaşi',
        'Uydu antenci',
        'Uzay mühendisi',
        'Uzay bilimcisi',
        'Uzman Jandarma',
        'Uzman Çavuş',
        'Üretici',
        'Ürolog',
        'Ütücü',
        'Üzümcü',
        'Üst Düzey Yönetici',
        'Vaiz',
        'Vali',
        'Vergi denetmeni',
        'Vergi müfettişi',
        'Vergi tahakkuk memuru',
        'Veritabani yöneticisi',
        'Veri hazirlama ve kontrol işletmeni',
        'Vestiyerci',
        'Veteriner hekim',
        'Veteriner sağlik teknikeri',
        'Veteriner sağlik teknisyeni',
        'Veznedar',
        'Video editörü',
        'Vinç operatörü',
        'Vitrinci',
        'Viyolonselci',
        'Vatman',
        'Yarbay',
        'Yardimci hakem',
        'Yardimci hizmetli',
        'Yardimci pilot',
        'Yargiç',
        'Yatirim uzmani',
        'Yayinci',
        'Yazar',
        'Yazi işleri müdürü',
        'Yazilim mühendisi',
        'Yelkenci',
        'Yeminli mali müşavir',
        'Yeminli tercüman',
        'Yer gösterici',
        'Yer teknisyeni',
        'Yerölçmeci',
        'Yoğurtçu',
        'Yol bekçisi',
        'Yorganci',
        'Yorumcu',
        'Yönetici',
        'Yüzücü',
        'Yönetmen',
        'Yikici',
        'Zabita',
        'Zoolog'
    )
    return jo

def follow():
    fo = (
        "facebook",
        "instagram",
        "youtube",
        "github",
        "linkedin",
        "web site",
    )
    return fo

def users():
    from django.contrib.auth.models import User
    user = []
    for i in User.objects.all():
        user.append(i.username)
    return user


def country():
    name_of_cities = [
        "adana",
        "adiyaman",
        "afyon",
        "ağri",
        "amasya",
        "ankara",
        "antalya",
        "artvin",
        "aydin",
        "balikesir",
        "bilecik",
        "bingöl",
        "bitlis",
        "bolu",
        "burdur",
        "bursa",
        "çanakkale",
        "çankiri",
        "çorum",
        "denizli",
        "diyarbakir",
        "edirne",
        "elaziğ",
        "erzincan",
        "erzurum",
        "eskişehir",
        "gaziantep",
        "giresun",
        "gümüşhane",
        "hakkari",
        "hatay",
        "isparta",
        "mersin",
        "istanbul",
        "izmir",
        "kars",
        "kastamonu",
        "kayseri",
        "Kirklareli",
        "kirşehir",
        "kocaeli",
        "konya",
        "kütahya",
        "malatya",
        "manisa",
        "kahramanmaraş",
        "mardin",
        "muğla",
        "muş",
        "nevşehir",
        "niğde",
        "ordu",
        "rize",
        "sakarya",
        "samsun",
        "siirt",
        "sinop",
        "sivas",
        "tekirdağ",
        "tokat",
        "trabzon",
        "tunceli",
        "şanliurfa",
        "uşak",
        "van",
        "yozgat",
        "zonguldak",
        "aksaray",
        "bayburt",
        "karaman",
        "kirikkale",
        "batman",
        "şirnak",
        "bartin",
        "ardahan",
        "iğdir",
        "yalova",
        "karabuk",
        "kilis",
        "osmaniye",
        "düzce",
        ]
    return name_of_cities    