# Generated by Django 2.0.12 on 2019-08-04 04:21

import core.cooggerapp.models.common
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreadedComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_count', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('last_update', models.DateTimeField(auto_now_add=True, verbose_name='Last update')),
                ('permlink', models.PositiveIntegerField(default=99999999999999)),
                ('body', models.TextField()),
                ('image_address', models.URLField(blank=True, null=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='threaded_comment.ThreadedComments')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
            bases=(models.Model, core.cooggerapp.models.common.View),
        ),
        migrations.AlterUniqueTogether(
            name='threadedcomments',
            unique_together={('user', 'permlink')},
        ),
    ]
