# Generated by Django 2.0.12 on 2019-08-11 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("threaded_comment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="threadedcomments",
            name="depth",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="threadedcomments",
            name="to",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="to",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
