# Generated by Django 2.0.12 on 2019-08-31 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("threaded_comment", "0002_auto_20190811_0640")]

    operations = [
        migrations.RemoveField(model_name="threadedcomments", name="last_update"),
        migrations.AddField(
            model_name="threadedcomments",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Last update"),
        ),
    ]
