# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-30 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooggerapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentlist',
            name='content_list',
            field=models.SlugField(max_length=30, verbose_name='İçerik listeniz'),
        ),
    ]
