# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-05 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooggerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='star',
            field=models.IntegerField(default=1, verbose_name='Yıldız'),
            preserve_default=False,
        ),
    ]
