# Generated by Django 2.0 on 2017-12-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooggerapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(blank=True, choices=[('muhendislik', 'mühendislik'), ('tip', 'tip'), ('fen-edebiyat', 'fen edebiyat'), ('iktisadi-ve-idari-bilimleri', 'i̇ktisadi ve idari bilimleri'), ('egitim', 'eğitim'), ('dis-hekimligi', 'diş hekimliği'), ('mimarlik', 'mimarlik'), ('islahiye-iktisadi-ve-idari-bilimleri', 'i̇slahiye iktisadi ve idari bilimleri'), ('guzel-sanatlar', 'güzel sanatlar'), ('saglik-bilimleri', 'sağlik bilimleri'), ('hukuk', 'hukuk'), ('ilahiyat', 'i̇lahiyat'), ('iletisim', 'i̇letişim'), ('havacilik-ve-uzay-muhendisligi', 'havacilik ve uzay mühendisliği'), ('turizm', 'turizm')], max_length=30, null=True, verbose_name='Fakülteler'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(verbose_name='İçeriğinizi yazın'),
        ),
    ]
