# Generated by Django 2.0 on 2018-01-04 14:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cooggerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='lastmod',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='son değiştirme tarihi'),
        ),
    ]
