# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-03 19:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cooggerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='tarih'),
        ),
    ]
