# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-29 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooggerapp', '0002_auto_20170929_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='new_content_list',
            field=models.CharField(default=1, max_length=30, verbose_name='Yeni liste oluşturun'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='content_list',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='İçerik listenizi seçin'),
        ),
    ]
