# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-03 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooggerapp', '0002_notification_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='dor',
            field=models.IntegerField(default=0, verbose_name='duration of read'),
        ),
    ]
