# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-17 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooggerapp', '0002_userfollow'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfollow',
            name='site',
            field=models.CharField(default=1, max_length=150, verbose_name='Adresi yazın'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userfollow',
            name='web_site',
            field=models.CharField(choices=[('facebook', 'facebook'), ('instagram', 'instagram'), ('youtube', 'youtube'), ('github', 'github'), ('linkedin', 'linkedin'), ('web-site', 'web site')], max_length=15),
        ),
    ]
