# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-01 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooggerapp', '0002_auto_20170930_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='dor',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='tag',
            field=models.CharField(max_length=200, verbose_name='İçeriğiniz ili ilgili anahtar kelimeleri virgul kullanarak yazın'),
        ),
    ]
