# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-26 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooggerapp', '0002_auto_20170924_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='user_topic',
            field=models.CharField(default=1, max_length=20, verbose_name='Liste seç'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('ders', 'ders'), ('oyun', 'oyun'), ('seyahat', 'seyahat'), ('giyim', 'giyim'), ('makyaj_ve_cilt_bakım', 'makyaj ve cilt bakım'), ('sağlık', 'sağlık'), ('yiyecek_ve_içecek', 'yiyecek ve içecek'), ('medya', 'medya'), ('ürün_eşya', 'ürün - eşya'), ('taşıtlar', 'taşıtlar'), ('tanınmış_kişi', 'tanınmış kişi'), ('hayvanlar', 'hayvanlar'), ('inanç', 'inanç'), ('dil', 'dil'), ('metafizik', 'metafizik'), ('aşk_arkadaşlık', 'aşk - arkadaşlık')], max_length=30, verbose_name='Kategori'),
        ),
    ]
