# Generated by Django 2.0 on 2017-12-17 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooggerapp', '0002_auto_20171217_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='category',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='subcategory',
        ),
    ]
