# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-29 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooggerapp', '0003_auto_20170929_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='new_content_list',
        ),
        migrations.AlterField(
            model_name='blog',
            name='content_list',
            field=models.CharField(default=1, max_length=30, verbose_name='İçeriğinizin liste ismini yazın'),
            preserve_default=False,
        ),
    ]
