# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-05 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooggerapp', '0003_auto_20171005_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='stars',
            field=models.IntegerField(default=0, verbose_name='Yıldız'),
        ),
    ]
