# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-11 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooggerapp', '0003_auto_20171011_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='show',
            field=models.CharField(max_length=400, verbose_name='İçeriğinizin anasayfadaki görünümünü ayarlayın'),
        ),
    ]
