# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-02 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooggerapp', '0003_auto_20171001_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='author',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='is_author',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='pp',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
