# Generated by Django 2.0 on 2017-12-17 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooggerapp', '0003_auto_20171217_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='dor',
            field=models.IntegerField(default=0, verbose_name='duration of read'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='show',
            field=models.TextField(max_length=400, verbose_name="Anasayfa'da görünecek içerik notu ekleyin"),
        ),
    ]
