# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-29 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooggerapp', '0004_auto_20170929_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentlist',
            name='content_count',
            field=models.IntegerField(default=1, verbose_name='liste içindeki nesne sayısı'),
            preserve_default=False,
        ),
    ]
