# Generated by Django 2.0 on 2017-12-17 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooggerapp', '0004_auto_20171218_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='dor',
            field=models.CharField(default=0, max_length=10, verbose_name='duration of read'),
        ),
    ]
