# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-17 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooggerapp', '0004_auto_20171017_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfollow',
            name='user',
            field=models.CharField(max_length=37),
        ),
    ]
