# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-02 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooggerapp', '0004_auto_20171003_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author',
            field=models.BooleanField(verbose_name='yazarlık başvurusu yaptımı'),
        ),
        migrations.AlterField(
            model_name='author',
            name='iban',
            field=models.CharField(max_length=24, verbose_name='iban numarası'),
        ),
        migrations.AlterField(
            model_name='author',
            name='is_author',
            field=models.BooleanField(verbose_name='yazar olarak kabul et'),
        ),
        migrations.AlterField(
            model_name='author',
            name='pp',
            field=models.BooleanField(verbose_name='profil resmi yüklemiş mi ?'),
        ),
    ]
