# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-11 00:51
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooggerapp', '0005_auto_20171011_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='show',
            field=ckeditor.fields.RichTextField(verbose_name='İçeriğinizin anasayfadaki görünümünü ayarlayın max : 400'),
        ),
    ]
