# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-03 00:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooggerapp', '0005_auto_20171003_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='iban',
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name='iban numarası'),
        ),
    ]
