# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-03 01:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooggerapp', '0006_auto_20171003_0314'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='telefon numarası'),
        ),
    ]
