# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-21 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooggerapp', '0007_auto_20171021_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='views',
            name='ip',
            field=models.CharField(max_length=200),
        ),
    ]
