# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-22 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooggerapp', '0008_auto_20171021_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='iban',
        ),
        migrations.AlterField(
            model_name='userfollow',
            name='user',
            field=models.CharField(choices=[('coogger', 'coogger'), ('hakancelik', 'hakancelik'), ('ibrahimsmngl', 'ibrahimsmngl'), ('ufukozer', 'ufukozer'), ('baristutakli', 'baristutakli'), ('imerafera', 'imerafera'), ('fadimekaplan', 'fadimekaplan'), ('vayra53', 'vayra53'), ('teibe', 'teibe'), ('ooznur', 'ooznur'), ('arslan', 'arslan'), ('saiddemir', 'saiddemir'), ('dersim67', 'dersim67'), ('omerculha', 'omerculha'), ('volkan_dere', 'volkan_dere')], max_length=37),
        ),
    ]
