# Generated by Django 2.0 on 2018-07-07 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooggerapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='category',
            new_name='left_side',
        ),
        migrations.RenameField(
            model_name='content',
            old_name='language',
            new_name='right_side',
        ),
        migrations.AddField(
            model_name='community',
            name='ms',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otherinformationofusers',
            name='community',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cooggerapp.Community'),
            preserve_default=False,
        ),
    ]
