# Generated by Django 2.0 on 2018-04-07 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooggerapp', '0002_auto_20180407_0302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['-time'], 'verbose_name': 'content'},
        ),
        migrations.RenameField(
            model_name='content',
            old_name='url',
            new_name='permlink',
        ),
    ]
