# Generated by Django 2.0 on 2018-07-07 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooggerapp', '0003_remove_otherinformationofusers_community'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='right_side',
            field=models.CharField(blank=True, choices=[('turkish', 'turkish'), ('english', 'english'), ('korean', 'korean'), ('spanish', 'spanish'), ('arabic', 'arabic'), ('french', 'french'), ('portuguese', 'portuguese'), ('german', 'german'), ('italian', 'italian'), ('japanese', 'japanese'), ('romanian', 'romanian'), ('russian', 'russian'), ('vietnamese', 'vietnamese '), ('arabic', 'arabic'), ('azerbaijani', 'azerbaijani')], help_text='The language of your content', max_length=30, null=True),
        ),
    ]
