# Generated by Django 2.0 on 2018-07-08 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooggerapp', '0004_auto_20180708_0115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otherinformationofusers',
            name='hmanycontent',
        ),
        migrations.AddField(
            model_name='community',
            name='client_id',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='community',
            name='code',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='community',
            name='host_name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='community',
            name='redirect_url',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='community',
            name='scope',
            field=models.CharField(default='vote,comment_options,comment,offline', max_length=200),
        ),
    ]
