# Generated by Django 2.0 on 2018-07-08 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooggerapp', '0005_auto_20180708_0317'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='app_secret',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
    ]
