# Generated by Django 2.0 on 2018-04-10 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooggerapp', '0005_auto_20180410_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='approved',
        ),
        migrations.AlterField(
            model_name='content',
            name='cantapproved',
            field=models.CharField(choices=[('approved', 'approved'), ('it-is-tutorial-content-but-too-short', 'it is tutorial content but too short.'), ('it-does-not-have-a-tutorial-content', 'it does not have a tutorial content.')], max_length=40, verbose_name='Why can not approved'),
        ),
    ]
