# Generated by Django 2.0 on 2018-04-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooggerapp', '0006_auto_20180410_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='approved',
            field=models.CharField(blank=True, choices=[('information-sharing', 'information sharing'), ('tutorial-content', 'tutorial content'), ('translation', 'translation')], max_length=40, null=True, verbose_name='Why approved'),
        ),
        migrations.AlterField(
            model_name='content',
            name='cantapproved',
            field=models.CharField(blank=True, choices=[('it-is-not-information-sharing', 'it is not information sharing.'), ('it-is-not-tutorial-content', 'it is not tutorial content.'), ('it-is-not-translationit-is-tutorial-content-but-not-enough-please-edit-and-reshare', 'it is not translationit is tutorial content but not enough, please edit and reshare'), ('it-is-information-sharing-but-not-enough-please-edit-and-reshare', 'it is information sharing but not enough, please edit and reshare'), ('it-is-translation-contribution-but-not-enough-please-edit-and-reshare', 'it is translation contribution but not enough, please edit and reshare'), ('fraud-or-plagiarism', 'fraud or plagiarism.'), ('hate-speech-or-internet-trolling', 'hate speech or internet trolling.'), ('intentional-miss-categorized-content-or-spam', 'intentional miss-categorized content or spam.')], max_length=40, null=True, verbose_name='Why can not approved'),
        ),
    ]
