# Generated by Django 2.0 on 2018-07-08 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooggerapp', '0006_community_app_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='login_redirect',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
