# Generated by Django 2.0 on 2018-07-08 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooggerapp', '0007_community_login_redirect'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='code',
        ),
    ]
