# Generated by Django 2.0 on 2018-07-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooggerapp', '0008_remove_community_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='left_side',
            field=models.CharField(choices=[('science', 'science'), ('tutorial', 'tutorial'), ('idea', 'idea'), ('project', 'project'), ('computer', 'computer'), ('language', 'language'), ('art', 'art'), ('technology', 'technology'), ('biography', 'biography'), ('books', 'books'), ('business', 'business'), ('media', 'media'), ('travel', 'travel'), ('health', 'health'), ('music', 'music'), ('food', 'food'), ('history', 'history'), ('finance', 'finance'), ('exchange', 'exchange'), ('design-graphic', 'design-graphic'), ('development', 'development'), ('question-answer', 'question-answer'), ('translation', 'translation'), ('discussion', 'discussion')], default=1, help_text='select content category', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='content',
            name='right_side',
            field=models.CharField(choices=[('turkish', 'turkish'), ('english', 'english'), ('korean', 'korean'), ('spanish', 'spanish'), ('arabic', 'arabic'), ('french', 'french'), ('portuguese', 'portuguese'), ('german', 'german'), ('italian', 'italian'), ('japanese', 'japanese'), ('romanian', 'romanian'), ('russian', 'russian'), ('vietnamese', 'vietnamese '), ('arabic', 'arabic'), ('azerbaijani', 'azerbaijani')], default=1, help_text='The language of your content', max_length=30),
            preserve_default=False,
        ),
    ]
