# Generated by Django 2.0 on 2018-07-10 01:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cooggerapp', '0009_auto_20180708_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooggerapp.Community')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='content',
            name='left_side',
            field=models.CharField(choices=[('turkish', 'turkish'), ('english', 'english'), ('korean', 'korean'), ('spanish', 'spanish'), ('arabic', 'arabic'), ('french', 'french'), ('portuguese', 'portuguese'), ('german', 'german'), ('italian', 'italian'), ('japanese', 'japanese'), ('romanian', 'romanian'), ('russian', 'russian'), ('vietnamese', 'vietnamese '), ('arabic', 'arabic'), ('azerbaijani', 'azerbaijani')], help_text='select content category', max_length=30),
        ),
        migrations.AlterField(
            model_name='content',
            name='right_side',
            field=models.CharField(choices=[('science', 'science'), ('tutorial', 'tutorial'), ('idea', 'idea'), ('project', 'project'), ('computer', 'computer'), ('language', 'language'), ('art', 'art'), ('technology', 'technology'), ('biography', 'biography'), ('books', 'books'), ('business', 'business'), ('media', 'media'), ('travel', 'travel'), ('health', 'health'), ('music', 'music'), ('food', 'food'), ('history', 'history'), ('finance', 'finance'), ('exchange', 'exchange'), ('design-graphic', 'design graphic'), ('development', 'development'), ('question-answer', 'question answer'), ('translation', 'translation'), ('discussion', 'discussion'), ('recipe', 'recipe'), ('food-blog', 'food-blog'), ('steemkitchen-contest-entry', 'steemkitchen contest entry'), ('steemit-iron-chef', 'steemit iron chef'), ('cook-with-us', 'cook with us'), ('food-photography', 'food photography')], help_text='The language of your content', max_length=30),
        ),
    ]
