# Generated by Django 2.0 on 2018-07-12 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooggerapp', '0010_auto_20180710_0407'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='left_side',
            new_name='language',
        ),
        migrations.RenameField(
            model_name='content',
            old_name='right_side',
            new_name='category',
        ),
    ]
