# Generated by Django 2.0 on 2018-06-20 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooggerapp', '0015_auto_20180620_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='source',
            field=models.CharField(default='', help_text='web address about this content - source', max_length=400),
        ),
        migrations.AlterField(
            model_name='content',
            name='type',
            field=models.CharField(choices=[('development', 'development'), ('design-graphic', 'design, graphic'), ('idea', 'idea'), ('question-answer', 'question ,answer'), ('information-sharing', 'information sharing'), ('tutorial-content', 'tutorial content'), ('translation', 'translation'), ('discussion', 'discussion')], help_text='select content type', max_length=30),
        ),
    ]
