# Generated by Django 2.0 on 2018-06-26 16:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cooggerapp', '0017_auto_20180626_0046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='type',
        ),
        migrations.AddField(
            model_name='content',
            name='category',
            field=models.CharField(choices=[('development', 'development'), ('design-graphic', 'design-graphic'), ('idea', 'idea'), ('question-answer', 'question-answer'), ('information-sharing', 'information-sharing'), ('tutorial-content', 'tutorial-content'), ('translation', 'translation'), ('discussion', 'discussion')], default=django.utils.timezone.now, help_text='select content category', max_length=30),
            preserve_default=False,
        ),
    ]
