# Generated by Django 2.0 on 2018-06-26 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooggerapp', '0019_auto_20180626_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='source',
        ),
    ]
