# Generated by Django 2.0 on 2018-07-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooggerapp', '0022_auto_20180627_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherinformationofusers',
            name='access_token',
            field=models.CharField(default=1, help_text='steemconnect user access_token to any operations', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otherinformationofusers',
            name='code',
            field=models.CharField(default=1, help_text='steemconnect user code / to get get_refresh_token', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otherinformationofusers',
            name='refresh_token',
            field=models.CharField(default=1, help_text='steemconnect user code / to get get_refresh_token', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='content',
            name='category',
            field=models.CharField(blank=True, choices=[('science', 'science'), ('tutorial', 'tutorial'), ('idea', 'idea'), ('project', 'project'), ('computer', 'computer'), ('language', 'language'), ('art', 'art'), ('technology', 'technology'), ('biography', 'biography'), ('books', 'books'), ('business', 'business'), ('media', 'media'), ('travel', 'travel'), ('health', 'health'), ('music', 'music'), ('food', 'food'), ('history', 'history'), ('finance', 'finance'), ('exchange', 'exchange'), ('design-graphic', 'design-graphic'), ('development', 'development'), ('question-answer', 'question-answer'), ('translation', 'translation'), ('discussion', 'discussion')], help_text='select content category', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='status',
            field=models.CharField(choices=[('shared', 'shared'), ('changed', 'changed'), ('rejected', 'rejected'), ('approved', 'approved')], default='shared', max_length=30, verbose_name="content's status"),
        ),
    ]
