# Generated by Django 2.0 on 2018-07-03 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooggerapp', '0023_auto_20180702_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otherinformationofusers',
            name='access_token',
        ),
        migrations.RemoveField(
            model_name='otherinformationofusers',
            name='code',
        ),
        migrations.RemoveField(
            model_name='otherinformationofusers',
            name='refresh_token',
        ),
    ]
