# Generated by Django 2.2.8 on 2019-12-19 23:16

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cooggerapp", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="commit",
            name="created",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="content",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime.now, verbose_name="Created"
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime.now, verbose_name="Created"
            ),
        ),
        migrations.AlterField(
            model_name="reportmodel",
            name="created",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
