# Generated by Django 3.0.3 on 2020-02-20 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cooggerapp", "0003_auto_20200217_0711"),
    ]

    operations = [
        migrations.AlterModelOptions(name="content", options={"ordering": ["order"]},),
        migrations.AlterField(
            model_name="content",
            name="order",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
