# Generated by Django 2.0 on 2018-03-18 02:35

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='tarih')),
                ('comment', models.CharField(max_length=310, verbose_name='Soru sor veya teşekkür et, yorum yap')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_list', models.CharField(default='coogger', help_text='İçeriğiniz belirli bir konu etrafında birden fazla olacak ise anlatacağınız konuyu yazın', max_length=30, verbose_name='Konu başlığınız')),
                ('title', models.CharField(help_text='İçeriğiniz ile alakalı en güzel başlığı seçtiğinizden emin olun.', max_length=100, verbose_name='Başlık')),
                ('url', models.CharField(max_length=200, unique=True, verbose_name='web adresi')),
                ('content', ckeditor.fields.RichTextField(verbose_name='İçeriğinizi yazın')),
                ('show', models.CharField(help_text='Okuyucularınıza içerik hakkında kısaca bilgi verin.', max_length=400, verbose_name='İçeriğinizin tanımı')),
                ('tag', models.CharField(help_text='anahtar kelimelerinizi virgül kullanarak yazın.', max_length=200, verbose_name='Anahtar kelimeler')),
                ('time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='tarih')),
                ('dor', models.CharField(default=0, max_length=10)),
                ('views', models.IntegerField(default=0, verbose_name='kişi görüntüledi')),
                ('read', models.IntegerField(default=0, verbose_name='sayfa açılma sayısı')),
                ('hmanycomment', models.IntegerField(default=0, verbose_name='yorum sayısı')),
                ('lastmod', models.DateTimeField(default=django.utils.timezone.now, verbose_name='son değiştirme tarihi')),
                ('confirmation', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'content',
                'ordering': ['-lastmod'],
            },
        ),
        migrations.CreateModel(
            name='Contentviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooggerapp.Content')),
            ],
        ),
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('which_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_requests_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('even', models.IntegerField(verbose_name='bildirime sebeb olan olay numarası')),
                ('content', models.CharField(max_length=310, verbose_name='bildirim mesajı')),
                ('show', models.BooleanField(default=False, verbose_name='gördü/görmedi')),
                ('address', models.SlugField(verbose_name='bildirimin gerçekleştiği adres')),
                ('time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='tarih')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='bildirimin gittiği kişi')),
            ],
        ),
        migrations.CreateModel(
            name='OtherInformationOfUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posting_key', models.CharField(max_length=250, verbose_name='steemit posting key')),
                ('about', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='kişi hakkında')),
                ('hmanycontent', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaints', models.CharField(choices=[('bilgi-teskil-etmiyor', 'bilgi teşkil etmiyor'), ('kopya-veya-calnt-icerik', 'kopya veya çalıntı içerik'), ('bunun-cooggerda-olmamas-gerek', "bunun coogger'da olmaması gerek")], max_length=40, verbose_name='şikayet türleri')),
                ('add', models.CharField(blank=True, max_length=600, null=True, verbose_name='Daha fazla bilgi vermek istermisin ?')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooggerapp.Content', verbose_name='şikayet edilen içerik')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='şikayet eden kişi')),
            ],
        ),
        migrations.CreateModel(
            name='SearchedWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=310, unique=True)),
                ('hmany', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='UserFollow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choices', models.CharField(choices=[('facebook', 'facebook'), ('instagram', 'instagram'), ('youtube', 'youtube'), ('github', 'github'), ('linkedin', 'linkedin'), ('web-site', 'web site')], max_length=15, verbose_name='Web sitesi')),
                ('adress', models.CharField(max_length=150, verbose_name='Adresi yazın')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooggerapp.Content'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='yorum yapan kişi'),
        ),
    ]
