# Generated by Django 2.0 on 2018-03-25 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_list', models.CharField(default='coogger', help_text='If your contents will continue around a particular topic, write your topic it down.', max_length=30, verbose_name='title of list')),
                ('title', models.CharField(help_text='Be sure to choose the best title related to your content.', max_length=100, verbose_name='Title')),
                ('url', models.CharField(max_length=200, unique=True, verbose_name='web address')),
                ('content', models.TextField(verbose_name='Write your content')),
                ('show', models.CharField(help_text='Briefly tell your readers about your content.', max_length=400, verbose_name='definition of content')),
                ('tag', models.CharField(help_text='Write your keywords using spaces max:4 .', max_length=200, verbose_name='keyword')),
                ('time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date')),
                ('dor', models.CharField(default=0, max_length=10)),
                ('views', models.IntegerField(default=0, verbose_name='views')),
                ('read', models.IntegerField(default=0, verbose_name='pageviews')),
                ('hmanycomment', models.IntegerField(default=0, verbose_name='comments count')),
                ('lastmod', models.DateTimeField(default=django.utils.timezone.now, verbose_name='last modified date')),
                ('confirmation', models.BooleanField(default=False, verbose_name='content approval')),
                ('draft', models.BooleanField(default=False, verbose_name='content draft')),
                ('cooggerup', models.BooleanField(default=False, verbose_name='upvote with cooggerup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'content',
                'ordering': ['-lastmod'],
            },
        ),
        migrations.CreateModel(
            name='Contentviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooggerapp.Content')),
            ],
        ),
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('which_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_requests_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OtherInformationOfUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(blank=True, null=True, verbose_name='About of user')),
                ('follower_count', models.IntegerField(default=0)),
                ('following_count', models.IntegerField(default=0)),
                ('hmanycontent', models.IntegerField(default=0)),
                ('cooggerup_confirmation', models.BooleanField(default=False, verbose_name='Do you want to join in curation trails of the cooggerup bot with your account?')),
                ('cooggerup_percent', models.CharField(choices=[('100', '100'), ('99', '99'), ('98', '98'), ('97', '97'), ('96', '96'), ('95', '95'), ('94', '94'), ('93', '93'), ('92', '92'), ('91', '91'), ('90', '90'), ('89', '89'), ('88', '88'), ('87', '87'), ('86', '86'), ('85', '85'), ('84', '84'), ('83', '83'), ('82', '82'), ('81', '81'), ('80', '80'), ('79', '79'), ('78', '78'), ('77', '77'), ('76', '76'), ('75', '75'), ('74', '74'), ('73', '73'), ('72', '72'), ('71', '71'), ('70', '70'), ('69', '69'), ('68', '68'), ('67', '67'), ('66', '66'), ('65', '65'), ('64', '64'), ('63', '63'), ('62', '62'), ('61', '61'), ('60', '60'), ('59', '59'), ('58', '58'), ('57', '57'), ('56', '56'), ('55', '55'), ('54', '54'), ('53', '53'), ('52', '52'), ('51', '51'), ('50', '50'), ('49', '49'), ('48', '48'), ('47', '47'), ('46', '46'), ('45', '45'), ('44', '44'), ('43', '43'), ('42', '42'), ('41', '41'), ('40', '40'), ('39', '39'), ('38', '38'), ('37', '37'), ('36', '36'), ('35', '35'), ('34', '34'), ('33', '33'), ('32', '32'), ('31', '31'), ('30', '30'), ('29', '29'), ('28', '28'), ('27', '27'), ('26', '26'), ('25', '25'), ('24', '24'), ('23', '23'), ('22', '22'), ('21', '21'), ('20', '20'), ('19', '19'), ('18', '18'), ('17', '17'), ('16', '16'), ('15', '15'), ('14', '14'), ('13', '13'), ('12', '12'), ('11', '11'), ('10', '10'), ('9', '9'), ('8', '8'), ('7', '7'), ('6', '6'), ('5', '5'), ('4', '4'), ('3', '3'), ('2', '2'), ('1', '1')], default=0, max_length=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReportModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaints', models.CharField(choices=[('bilgi-teskil-etmiyor', 'bilgi teşkil etmiyor'), ('kopya-veya-calnt-icerik', 'kopya veya çalıntı içerik'), ('bunun-cooggerda-olmamas-gerek', "bunun coogger'da olmaması gerek")], max_length=40, verbose_name='şikayet türleri')),
                ('add', models.CharField(blank=True, max_length=600, null=True, verbose_name='Daha fazla bilgi vermek istermisin ?')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooggerapp.Content', verbose_name='şikayet edilen içerik')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='şikayet eden kişi')),
            ],
        ),
        migrations.CreateModel(
            name='SearchedWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=310, unique=True)),
                ('hmany', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='UserFollow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choices', models.CharField(choices=[('facebook', 'facebook'), ('instagram', 'instagram'), ('youtube', 'youtube'), ('github', 'github'), ('linkedin', 'linkedin'), ('web-site', 'web site')], max_length=15, verbose_name='Web sitesi')),
                ('adress', models.CharField(max_length=150, verbose_name='Adresi yazın')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
