# Generated by Django 2.0 on 2018-03-21 19:31

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='tarih')),
                ('comment', models.CharField(max_length=310, verbose_name='Soru sor veya teşekkür et, yorum yap')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_list', models.CharField(default='coogger', help_text='If your contents will continue around a particular topic, write your topic it down.', max_length=30, verbose_name='title of list')),
                ('title', models.CharField(help_text='Be sure to choose the best title related to your content.', max_length=100, verbose_name='Title')),
                ('url', models.CharField(max_length=200, unique=True, verbose_name='web address')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Write your content')),
                ('show', models.CharField(help_text='Briefly tell your readers about your content.', max_length=400, verbose_name='definition of content')),
                ('tag', models.CharField(help_text='Write your keywords using spaces max:4 .', max_length=200, verbose_name='keyword')),
                ('time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date')),
                ('dor', models.CharField(default=0, max_length=10)),
                ('views', models.IntegerField(default=0, verbose_name='views')),
                ('read', models.IntegerField(default=0, verbose_name='pageviews')),
                ('hmanycomment', models.IntegerField(default=0, verbose_name='comments count')),
                ('lastmod', models.DateTimeField(default=django.utils.timezone.now, verbose_name='last modified date')),
                ('confirmation', models.BooleanField(default=False, verbose_name='content approval')),
                ('draft', models.BooleanField(default=False, verbose_name='content draft')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'content',
                'ordering': ['-lastmod'],
            },
        ),
        migrations.CreateModel(
            name='Contentviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooggerapp.Content')),
            ],
        ),
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('which_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_requests_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('even', models.IntegerField(verbose_name='bildirime sebeb olan olay numarası')),
                ('content', models.CharField(max_length=310, verbose_name='bildirim mesajı')),
                ('show', models.BooleanField(default=False, verbose_name='gördü/görmedi')),
                ('address', models.SlugField(verbose_name='bildirimin gerçekleştiği adres')),
                ('time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='tarih')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='bildirimin gittiği kişi')),
            ],
        ),
        migrations.CreateModel(
            name='OtherInformationOfUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='About of user')),
                ('follower_count', models.IntegerField(default=0)),
                ('following_count', models.IntegerField(default=0)),
                ('hmanycontent', models.IntegerField(default=0)),
                ('cooggerup_confirmation', models.BooleanField(default=False, verbose_name='Do you want to join in curation trails of the cooggerup bot with your account?')),
                ('cooggerup_percent', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31'), ('32', '32'), ('33', '33'), ('34', '34'), ('35', '35'), ('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44'), ('45', '45'), ('46', '46'), ('47', '47'), ('48', '48'), ('49', '49'), ('50', '50'), ('51', '51'), ('52', '52'), ('53', '53'), ('54', '54'), ('55', '55'), ('56', '56'), ('57', '57'), ('58', '58'), ('59', '59'), ('60', '60'), ('61', '61'), ('62', '62'), ('63', '63'), ('64', '64'), ('65', '65'), ('66', '66'), ('67', '67'), ('68', '68'), ('69', '69'), ('70', '70'), ('71', '71'), ('72', '72'), ('73', '73'), ('74', '74'), ('75', '75'), ('76', '76'), ('77', '77'), ('78', '78'), ('79', '79'), ('80', '80'), ('81', '81'), ('82', '82'), ('83', '83'), ('84', '84'), ('85', '85'), ('86', '86'), ('87', '87'), ('88', '88'), ('89', '89'), ('90', '90'), ('91', '91'), ('92', '92'), ('93', '93'), ('94', '94'), ('95', '95'), ('96', '96'), ('97', '97'), ('98', '98'), ('99', '99'), ('100', '100')], default=0, max_length=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReportModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaints', models.CharField(choices=[('bilgi-teskil-etmiyor', 'bilgi teşkil etmiyor'), ('kopya-veya-calnt-icerik', 'kopya veya çalıntı içerik'), ('bunun-cooggerda-olmamas-gerek', "bunun coogger'da olmaması gerek")], max_length=40, verbose_name='şikayet türleri')),
                ('add', models.CharField(blank=True, max_length=600, null=True, verbose_name='Daha fazla bilgi vermek istermisin ?')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooggerapp.Content', verbose_name='şikayet edilen içerik')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='şikayet eden kişi')),
            ],
        ),
        migrations.CreateModel(
            name='SearchedWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=310, unique=True)),
                ('hmany', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='UserFollow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choices', models.CharField(choices=[('facebook', 'facebook'), ('instagram', 'instagram'), ('youtube', 'youtube'), ('github', 'github'), ('linkedin', 'linkedin'), ('web-site', 'web site')], max_length=15, verbose_name='Web sitesi')),
                ('adress', models.CharField(max_length=150, verbose_name='Adresi yazın')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooggerapp.Content'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='yorum yapan kişi'),
        ),
    ]
