# Generated by Django 2.0 on 2018-03-24 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooggerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='upvote',
            field=models.BooleanField(default=False, verbose_name='did it get support from that cooggerup'),
        ),
        migrations.AlterField(
            model_name='content',
            name='cooggerup',
            field=models.BooleanField(default=False, verbose_name='upvote from cooggerup'),
        ),
    ]
