# Generated by Django 2.0 on 2018-03-24 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooggerapp', '0002_auto_20180324_0332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='upvote',
        ),
        migrations.AlterField(
            model_name='content',
            name='cooggerup',
            field=models.BooleanField(default=False, verbose_name='upvote with cooggerup'),
        ),
    ]
