# Generated by Django 2.0 on 2018-04-10 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooggerapp', '0003_auto_20180407_0327'),
    ]

    operations = [
        migrations.CreateModel(
            name='CooggerUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False, verbose_name='content approval')),
                ('cantapproved', models.CharField(choices=[('it-is-tutorial-content-but-too-short', 'it is tutorial content but too short.'), ('it-does-not-have-a-tutorial-content', 'it does not have a tutorial content.')], default=False, max_length=40, verbose_name='Neden onaylanmadı')),
                ('cooggerup', models.BooleanField(default=False, verbose_name='upvote with cooggerup bot')),
                ('upvote', models.BooleanField(default=False, verbose_name='was voting done')),
            ],
        ),
        migrations.RenameField(
            model_name='content',
            old_name='show',
            new_name='definition',
        ),
        migrations.RemoveField(
            model_name='content',
            name='confirmation',
        ),
        migrations.RemoveField(
            model_name='content',
            name='cooggerup',
        ),
        migrations.RemoveField(
            model_name='content',
            name='upvote',
        ),
        migrations.AlterField(
            model_name='content',
            name='permlink',
            field=models.CharField(max_length=200, unique=True, verbose_name='permlink'),
        ),
        migrations.AlterField(
            model_name='reportmodel',
            name='add',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Can you give more information ?'),
        ),
        migrations.AlterField(
            model_name='reportmodel',
            name='complaints',
            field=models.CharField(choices=[('fraud-or-plagiarism', 'fraud or plagiarism'), ('hate-speech-or-internet-trolling', 'hate speech or internet trolling'), ('intentional-miss-categorized-content-or-spam', 'intentional miss-categorized content or spam'), ('this-content-is-not-tutorial-content', 'this content is not tutorial content'), ('wrong-list-name', 'wrong list name'), ('i-think-this-content-should-not-be-at-coogger', 'i think this content should not be at coogger')], max_length=40, verbose_name='type of report'),
        ),
        migrations.AlterField(
            model_name='userfollow',
            name='adress',
            field=models.CharField(max_length=150, verbose_name='write address / username'),
        ),
        migrations.AlterField(
            model_name='userfollow',
            name='choices',
            field=models.CharField(choices=[('facebook', 'facebook'), ('instagram', 'instagram'), ('youtube', 'youtube'), ('github', 'github'), ('linkedin', 'linkedin'), ('web-site', 'web site')], max_length=15, verbose_name='website'),
        ),
        migrations.AddField(
            model_name='cooggerup',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooggerapp.Content', verbose_name='şikayet edilen içerik'),
        ),
    ]
