# Generated by Django 2.0 on 2018-04-10 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooggerapp', '0004_auto_20180410_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cooggerup',
            name='content',
        ),
        migrations.AddField(
            model_name='content',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='approved'),
        ),
        migrations.AddField(
            model_name='content',
            name='cantapproved',
            field=models.CharField(choices=[('none', 'none'), ('it-is-tutorial-content-but-too-short', 'it is tutorial content but too short.'), ('it-does-not-have-a-tutorial-content', 'it does not have a tutorial content.')], default=1, max_length=40, verbose_name='Why can not approved'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content',
            name='cooggerup',
            field=models.BooleanField(default=False, verbose_name='upvote with cooggerup bot'),
        ),
        migrations.AddField(
            model_name='content',
            name='upvote',
            field=models.BooleanField(default=False, verbose_name='was voting done'),
        ),
        migrations.DeleteModel(
            name='CooggerUp',
        ),
    ]
