# Generated by Django 2.0 on 2018-04-12 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cooggerapp', '0008_auto_20180411_1905'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['-time']},
        ),
        migrations.AddField(
            model_name='content',
            name='mod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='content',
            name='content_list',
            field=models.SlugField(help_text='If your contents will continue around a particular topic, write your topic it down.', max_length=30, verbose_name='title of list'),
        ),
        migrations.AlterField(
            model_name='content',
            name='permlink',
            field=models.SlugField(max_length=200),
        ),
        migrations.AlterField(
            model_name='following',
            name='which_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='which_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
