# Generated by Django 2.0.12 on 2019-08-19 13:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cooggerapp", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="contributors",
            field=models.ManyToManyField(
                blank=True,
                related_name="content_contributors",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="utopic",
            name="contributors",
            field=models.ManyToManyField(
                blank=True,
                related_name="utopic_contributors",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
